/* SPDX-License-Identifier: GPL-2.0 */
/*
 *  Copyright (C) 2022-2022 Tsingmicro, Inc.
 */

#ifndef _DT_BINDINGS_TS_TX5336_RESETS_H
#define _DT_BINDINGS_TS_TX5336_RESETS_H

#define TS_GIC_RST						0
#define TS_CPU_DAP_SYS_RST				1
#define TS_CPU_DAP_DEBUG_RST			2
#define TS_CV_SYS_ALL_RST				3
#define TS_VPU_SYS_ALL_RST				4
#define TS_RNE_SYS_ALL_RST				5
#define TS_DDR_SYS_ALL_RST				7
#define TS_VI_SYS_ALL_RST				8
#define TS_WDT_T_RST					9
#define TS_WDT_APB_RST					10
#define TS_GPIO_APB_RST					12
#define TS_SYSREG_APB_RST				13
#define TS_IOMUX_APB_RST				14
#define TS_GPADC_APB_RST				15
#define TS_OTPC_APB_RST					16
#define TS_USI1_APB_RST					17
#define TS_USI0_APB_RST					18
#define TS_PWM_APB_RST					19
#define TS_HDMA1_AHB_RST				20
#define TS_HDMA0_AHB_RST				21
#define TS_QSPI_REF_RST					22
#define TS_QSPI_AHB_RST					23
#define TS_QSPI_APB_RST					25
#define TS_AUD_CODEC_AHB_RST			27
#define TS_SPI1_CORE_RST				29
#define TS_SPI1_APB_RST					31
#define TS_SPI0_CORE_RST				33
#define TS_SPI0_APB_RST					35
#define TS_SPI2_CORE_RST				37
#define TS_SPI2_APB_RST					38
#define TS_TIMER0_5_RST					39
#define TS_TIMER0_4_RST					41
#define TS_TIMER0_3_RST					43
#define TS_TIMER0_2_RST					44
#define TS_TIMER0_1_RST					46
#define TS_TIMER0_APB_RST				47
#define TS_TIMER0_8_RST					48
#define TS_TIMER0_7_RST					49
#define TS_TIMER0_6_RST					50
#define TS_TIMER1_5_RST					51
#define TS_TIMER1_4_RST					52
#define TS_TIMER1_3_RST					53
#define TS_TIMER1_2_RST					54
#define TS_TIMER1_1_RST					55
#define TS_TIMER1_APB_RST				56
#define TS_TIMER1_8_RST					57
#define TS_TIMER1_7_RST					58
#define TS_TIMER1_6_RST					59
#define TS_I2C1_CORE_RST				60
#define TS_I2C1_APB_RST					61
#define TS_I2C0_CORE_RST				62
#define TS_I2C0_APB_RST					63
#define TS_I2C3_CORE_RST				64
#define TS_I2C3_APB_RST					65
#define TS_I2C2_CORE_RST				66
#define TS_I2C2_APB_RST					67
#define TS_I2C5_CORE_RST				68
#define TS_I2C5_APB_RST					69
#define TS_I2C4_CORE_RST				70
#define TS_I2C4_APB_RST					73
#define TS_I2C6_CORE_RST				76
#define TS_I2C6_APB_RST					77
#define TS_UART3_CORE_RST				78
#define TS_UART3_APB_RST				79
#define TS_UART2_CORE_RST				80
#define TS_UART2_APB_RST				81
#define TS_UART1_CORE_RST				82
#define TS_UART1_APB_RST				83
#define TS_UART0_CORE_RST				84
#define TS_UART0_APB_RST				85
#define TS_I2S_CORE_RST					86
#define TS_I2S_APB_RST					87
#define TS_SDHCI0_AHB_RST				88
#define TS_SDHCI1_AHB_RST				89
#define TS_USB_PHY_RST					90
#define TS_USB_AHB_RST					91
#define TS_GMAC_AXI_RST					92
#define TS_GMAC_AHB_RST					93
#define TS_DDRPHY_RST					94
#define TS_DDRC_CORE_RST				95
#define TS_DDRPHY_APB_RST				96
#define TS_DDRC_APB_RST					97
#define TS_DDR_PORT1_RST				98
#define TS_DDR_PORT0_RST				99
#define TS_DDR_PORT3_RST				100
#define TS_DDR_PORT2_RST				101
#define TS_DDR_PORT5_RST				102
#define TS_DDR_PORT4_RST				103
#define TS_RNE_CORE_RST					104
#define TS_RNE_AXI_RST					105
#define TS_RNE_AHB_RST					106
#define TS_RNE_MEMBUF_RST				107
#define TS_VI_APB_BUS_RST				108
#define TS_ISP_CORE_RST					109
#define TS_ISP_AXI_RST					110
#define TS_ISP_AHB_RST					111
#define TS_VPE_CORE_RST					112
#define TS_VPE_ISP_RST					113
#define TS_VPE_AXI_RST					114
#define TS_VPE_AHB_RST					115
#define TS_DOF_CORE_RST					116
#define TS_DOF_AXI_RST					117
#define TS_DOF_APB_RST					118
#define TS_EBD_CORE_RST					119
#define TS_EBD_AXI_RST					120
#define TS_EBD_AHB_RST					122
#define TS_MIPI_RXPHY1_APB_RST			124
#define TS_MIPI_RXPHY0_APB_RST			125
#define TS_MIPI_CSI3_APB_RST			127
#define TS_MIPI_CSI2_APB_RST			128
#define TS_MIPI_CSI1_APB_RST			129
#define TS_MIPI_CSI0_APB_RST			130
#define TS_BOOTROM_AHB_RST				132
#define TS_CV_APB_BUS_RST				133
#define TS_TRNG_RST						134
#define TS_PKE_RST						135
#define TS_SPACC_RST					136
#define TS_SKE_RST						137
#define TS_HASH_RST						138
#define TS_AMR_CORE_RST					140
#define TS_AMR_AXI_RST					141
#define TS_AMR_AHB_RST					142
#define TS_CVE_CORE_RST					143
#define TS_CVE_AXI_RST					144
#define TS_CVE_AHB_RST					145
#define TS_BIS_CORE_RST					148
#define TS_BIS_AXI_RST					149
#define TS_BIS_APB_RST					150
#define TS_GDC_CORE_RST					152
#define TS_GDC_AXI_RST					153
#define TS_GDC_APB_RST					154
#define TS_DPU_ALL_RST					155
#define TS_MIPI_TXPHY_APB_RST			156
#define TS_MIPI_DSI_APB_RST				157
#define TS_ADMA_AXI_RST					159
#define TS_ADMA_AHB_RST					160
#define TS_PDM1_M_RST					161
#define TS_PDM1_APB_RST					162
#define TS_PDM0_M_RST					163
#define TS_PDM0_APB_RST					164
#define TS_PDM3_M_RST					165
#define TS_PDM3_APB_RST					166
#define TS_PDM2_M_RST					167
#define TS_PDM2_APB_RST					168
#define TS_VPU_CORE_RST					170
#define TS_RST_MAX						171


#endif
