
obj-$(CONFIG_RTL8367RBVB_SWITCH) += acl.o chip.o cpu.o dot1x.o eee.o gpio.o i2c.o igmp.o interrupt.o l2.o leaky.o led.o mirror.o oam.o port.o ptp.o qos.o rate.o rldp.o rtk_switch.o stat.o storm.o svlan.o trap.o trunk.o vlan.o
obj-$(CONFIG_RTL8367RBVB_SWITCH) += switch_adapt.o
obj-$(CONFIG_RTL8367RBVB_SWITCH) += dal/dal_mgmt.o
obj-y += dal/rtl8367c/
