// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (C) 2022-2022 Tsingmicro, Inc.
 */
#include <asm/io.h>
#include <dt-bindings/clock/ts-tx536-clk.h>
#include <dm.h>
#include <log.h>
#include <mapmem.h>
#include "ts_pll.h"
#include "ts_clk.h"

/* TOP_CGU */
#define CPU_PLL_CFG0			0x000
#define CPU_PLL_CFG1			0x004
#define CPU_PLL_CFG2			0x008
#define CPU_PLL_EN				0x00C
#define BUS_PLL_CFG0			0x010
#define BUS_PLL_CFG1			0x014
#define BUS_PLL_CFG2			0x018
#define BUS_PLL_EN				0x01C
#define DDR_PLL_CFG0			0x020
#define DDR_PLL_CFG1			0x024
#define DDR_PLL_CFG2			0x028
#define DDR_PLL_EN				0x02C
#define DISP_PLL_CFG0			0x030
#define DISP_PLL_CFG1			0x034
#define DISP_PLL_CFG2			0x038
#define DISP_PLL_EN				0x03C
#define AUD_PLL_CFG0			0x040
#define AUD_PLL_CFG1			0x044
#define AUD_PLL_CFG2			0x048
#define AUD_PLL_EN				0x04C
#define AI_PLL_CFG0				0x200
#define AI_PLL_CFG1				0x204
#define AI_PLL_CFG2				0x208
#define AI_PLL_EN				0x20C
#define PLL_STATUS				0x050

#define A53_CLK_CFG0			0x060
#define A53_CLK_CFG1			0x064
#define CX400_CLK_CFG			0x070
#define CX400_CLK_EN			0x074
#define TOP_NOC_CLK_CFG			0x080
#define TOP_BUS_CLK_EN0			0x084
#define TOP_BUS_CLK_EN1			0x088
#define TOP_BUS_CLK_EN2			0x08C
#define TOP_BUS_CLK_EN3			0x090
#define TOP_BUS_CLK_EN4			0x094
#define TOP_BUS_CLK_EN5			0x098
#define GMAC_ACLK_CFG			0x09C
#define MSHC_BUS_CLK_CFG		0x0A0
#define MSHC0_CCLK_CFG0			0x0A4
#define MSHC1_CCLK_CFG0			0x0A8
#define USB3_FUNC_CLK_CFG		0x0AC
#define USB3_BUS_CLK_CFG		0x0B0
#define CRYPTO_BUS_CLK_CFG		0x0B4
#define NFC_CLKB_CFG			0x0B8
#define GDC_CLK_CFG				0x0BC
#define BT1120_CLK_CFG			0x0C0
#define OSPI_HCLK_CFG			0x0C8
#define OSPI_REF_CLK_CFG		0x0CC
#define CVE_CLK_CFG				0x0D0
#define GPU_CLK_CFG				0x0D4
#define I2S_CLK_CFG				0x0DC
#define I2C_ICCLK_CFG0			0x0E0
#define I2C_ICCLK_CFG1			0x0E4
#define I2C_ICCLK_CFG2			0x0E8
#define I2C_ICCLK_CFG3			0x0EC
#define UART1_SCLK_CFG			0x0F0
#define UART2_SCLK_CFG			0x0F4
#define UART3_SCLK_CFG			0x0F8
#define UART4_SCLK_CFG			0x0FC
#define UART5_SCLK_CFG			0x100
#define UART6_SCLK_CFG			0x104
#define SPI_SCLK_CFG0			0x110
#define SPI_SCLK_CFG1			0x114
#define SPI_SCLK_CFG2			0x118
#define TOP_TMR_TCK_EN			0x120
#define TOP_TMR_TCK_CFG			0x124
#define SEC_TMR_TCK_EN			0x128
#define SEC_TMR_TCK_CFG			0x12C
#define CHIP_OUT_CLK_CFG0		0x130
#define CHIP_OUT_CLK_CFG1		0x134
#define GMAC_MAC_CLK_EN			0x140
#define GMAC_MAC_CLK_MODE		0x144
#define GMAC_TX_CLK_DLY			0x148
#define GMAC_RX_CLK_DLY			0x14C
#define EPHY_REF_CLK_CFG		0x150
#define VO_BUS_CLK_CFG			0x160
#define VO_SYS_CLK_EN0			0x164
#define VO_SYS_CLK_EN1			0x168
#define DP650_CLK_CFG			0x170
#define DMA2MIPI_CLK_CFG		0x178
#define NEMADC_CLK_CFG			0x180
#define HDMI_TX_CLK_CFG			0x188
#define DDR_CTL_CLK_EN			0x1A0
#define DDR_CTL_CLK_CFG0		0x1A4
#define DDR_CTL_CLK_CFG1		0x1A8
#define VI_BUS_CLK_CFG			0x1C0
#define VI_BUS_CLK_EN			0x1C4
#define VPE_CLK_CFG				0x1C8
#define ISP_CLK_CFG				0x1D0
#define VI_FUNC_CLK_EN0			0x1D8
#define VI_FUNC_CLK_EN1			0x1DC
#define VPU_BUS_CLK_CFG			0x1F0
#define VPU_BUS_CLK_EN			0x1F4
#define WAVE_FUNC_CLK_CFG		0x1F8
#define CODA_FUNC_CLK_CFG		0x1FC
#define AI_BUS_CLK_EN			0x210
#define AI_BUS_CLK_CFG			0x214
#define RCE_CCLK_CFG			0x218
#define RNE_CCLK_CFG			0x21C
#define AI_CLK_MOD_CFG			0x220

/* MCU_CRGU */
#define MCU_PLL_CFG0			0x000
#define MCU_PLL_CFG1			0x004
#define MCU_PLL_CFG2			0x008
#define MCU_PLL_EN				0x00C
#define MCU_PLL_STATUS			0x010
#define MCU_BUS_CLK_CFG0		0x020
#define MCU_BUS_CLK_CFG1		0x024
#define MCU_BUS_CLK_CFG2		0x028
#define MCU_BUS_CLK_EN0			0x030
#define MCU_BUS_CLK_EN1			0x034
#define DVP_CLK_CFG				0x040
#define AUD_CLK_CFG				0x048
#define UART0_CLK_CFG			0x050
#define I2C0_CLK_CFG			0x060
#define I2C1_CLK_CFG			0x064
#define MCU_TMR_CLK_CFG			0x070
#define MCU_TMR_CLK_EN			0x074
#define MCU_CLK24M_EN			0x080
#define CHIP_OCLK4_CFG			0x088

/* All methods are delegated to CCF clocks */

/* Parents for muxed clocks */
static const char * const a53_clkin_sels[] = { &osc_in[0], "cpu_pll" };
static const char * const cx400_clk_sels[] = { &osc_in[0], "cpu_pll_d4" };
static const char * const top_noc_clk_sels[] = { &osc_in[0], "bus_pll" };
static const char * const mshc_hclk_sels[] = { &osc_in[0], "bus_pll_d6" };
static const char * const crypto_bus_clk_sels[] = { &osc_in[0], "bus_pll_d2" };
static const char * const usb3c_bus_clk_sels[] = { &osc_in[0], "bus_pll_d4" };
static const char * const gdc_aclk_sels[] = { &osc_in[0], "bus_pll_d2" };
static const char * const cve_aclk_sels[] = { &osc_in[0], "bus_pll_d2" };
static const char * const gpu_aclk_sels[] = { &osc_in[0], "bus_pll_d2" };
static const char * const gmac_aclk_sels[] = { &osc_in[0], "bus_pll_d6" };
static const char * const mshc_bclk_sels[] = { &osc_in[0], "cpu_pll_d2" };
static const char * const usb_phy_refclk_sels[] = {
	"cpu_pll_d64", "cpu_pll_d16", &osc_in[0] };
static const char * const usb_ctl_refclk_sels[] = { &osc_in[0], "bus_pll_d16" };
static const char * const nfc_clkb_sels[] = { &osc_in[0], "cpu_pll_d8" };
static const char * const bt1120_aclk_sels[] = { &osc_in[0], "bus_pll_d6" };
static const char * const ospi_hclk_sels[] = { &osc_in[0], "bus_pll_d6" };
static const char * const ospi_ref_clk_sels[] = { &osc_in[0], "bus_pll_d4" };
static const char * const i2c_2_9_icclk_sels[] = { &osc_in[0], "cpu_pll_d8" };
static const char * const uart_1_6_sclk_sels[] = { &osc_in[0], "cpu_pll_d2" };
static const char * const spi_ssiclk_sels[] = { &osc_in[0], "cpu_pll_d8" };
static const char * const chip_out_clk_sels[] = {
	"disp_pll_d32", "disp_pll_d16", "cpu_pll_d64", "cpu_pll_d32",
	"mcu_pll_d108", "mcu_pll_d54", "mcu_pll_d36", "mcu_pll_d18",
	"mcu_pll_d48", "mcu_pll_d24" };
static const char * const dma2mipi_txphy_clk_sels[] = {
	&osc_in[0], "mcu_pll_d54" };
static const char * const isp_sclk_sels[] = {
	"cpu_pll_d6", "cpu_pll_d4", "bus_pll_d4" };
static const char * const mipi_rxphy_cfgclk_sels[] = {
	&osc_in[0], "mcu_pll_d54" };
static const char * const ai_mem_aclk_sels[] = { &osc_in[0], "cpu_pll_d2" };
static const char * const mcu_noc_clk_sels[] = { &osc_in[0], "mcu_pll_d2" };
static const char * const mcu_ddr_aclk_sels[] = { &osc_in[0], "bus_pll" };
static const char * const aud_pclk_sels[] = { &osc_in[0], "mcu_pll_d54" };
static const char * const aud_mclk_sels[] = { &osc_in[0], "mcu_pll_d54" };
static const char * const uart0_sclk_sels[] = { &osc_in[0], "mcu_pll_d3" };
static const char * const i2c_0_1_icclk_sels[] = { &osc_in[0], "mcu_pll_d6" };

/*
 * All parameters for different sub-clocks are collected into parameter arrays.
 * These parameters are then initialized by the clock which uses them during
 * probe. To save space, ids are automatically generated for each sub-clock by
 * using an enum. Instead of storing a parameter struct for each clock, even for
 * those clocks which don't use a particular type of sub-clock, we can just
 * store the parameters for the clocks which need them.
 *
 * So why do it like this? Arranging all the sub-clocks together makes it very
 * easy to find bugs in the code.
 */

#define DIV(id, off, shift, width, sync) DIV_FLAGS(id, off, shift, width, WE_INVALID, sync, 0)
#define DIV_LIST \
	DIV(TS_CLK_TX536_A53_CLKIN, A53_CLK_CFG0, 4, 4, 8) \
	DIV(TS_CLK_TX536_A53_DBG_PCLK, A53_CLK_CFG1, 0, 3, 3) \
	DIV(TS_CLK_TX536_A53_ATCLK, A53_CLK_CFG1, 4, 2, 7) \
	DIV(TS_CLK_TX536_A53_ACLKM, A53_CLK_CFG1, 8, 2, 11) \
	DIV(TS_CLK_TX536_A53_CNT_CLK, A53_CLK_CFG1, 12, 4, 16) \
	DIV(TS_CLK_TX536_DMAC_1_ACP_ACLK, A53_CLK_CFG1, 20, 2, 23) \
	DIV(TS_CLK_TX536_CX400_ATCLK, CX400_CLK_CFG, 4, 2, 7) \
	DIV(TS_CLK_TX536_CX400_DAP_CLK, CX400_CLK_CFG, 0, 2, 3) \
	DIV(TS_CLK_TX536_TOP_NOC_CLK, TOP_NOC_CLK_CFG, 4, 3, 7) \
	DIV(TS_CLK_TX536_TOP_BUS_HCLK, TOP_NOC_CLK_CFG, 8, 3, 11) \
	DIV(TS_CLK_TX536_TOP_BUS_PCLK, TOP_NOC_CLK_CFG, 12, 2, 15) \
	DIV(TS_CLK_TX536_MSHC_0_HCLK, MSHC_BUS_CLK_CFG, 4, 4, 8) \
	DIV(TS_CLK_TX536_MSHC_1_HCLK, MSHC_BUS_CLK_CFG, 20, 4, 24) \
	DIV(TS_CLK_TX536_CRYPTO_BUS_CLK, CRYPTO_BUS_CLK_CFG, 0, 2, 3) \
	DIV(TS_CLK_TX536_USB3C_BUS_CLK, USB3_BUS_CLK_CFG, 0, 3, 3) \
	DIV(TS_CLK_TX536_GDC_ACLK, GDC_CLK_CFG, 0, 4, 4) \
	DIV(TS_CLK_TX536_CVE_ACLK, CVE_CLK_CFG, 4, 3, 7) \
	DIV(TS_CLK_TX536_GPU_ACLK, GPU_CLK_CFG, 4, 6, 11) \
	DIV(TS_CLK_TX536_GMAC_ACLK, GMAC_ACLK_CFG, 0, 3, 3) \
	DIV(TS_CLK_TX536_MSHC_0_BCLK, MSHC0_CCLK_CFG0, 16, 3, 19) \
	DIV(TS_CLK_TX536_MSHC_1_BCLK, MSHC1_CCLK_CFG0, 16, 3, 19) \
	DIV(TS_CLK_TX536_NFC_CLKB, NFC_CLKB_CFG, 4, 3, 7) \
	DIV(TS_CLK_TX536_GDC_MCLK, GDC_CLK_CFG, 8, 3, 11) \
	DIV(TS_CLK_TX536_BT1120TX_ACLK, BT1120_CLK_CFG, 0, 3, 3) \
	DIV(TS_CLK_TX536_BT1120RX_ACLK, BT1120_CLK_CFG, 8, 3, 11) \
	DIV(TS_CLK_TX536_BT1120TX_HCLK, BT1120_CLK_CFG, 16, 3, 19) \
	DIV(TS_CLK_TX536_OSPI_HCLK, OSPI_HCLK_CFG, 4, 3, 7) \
	DIV(TS_CLK_TX536_OSPI_REF_CLK, OSPI_REF_CLK_CFG, 4, 4, 8) \
	DIV(TS_CLK_TX536_CVE_CCLK, CVE_CLK_CFG, 12, 3, 15) \
	DIV(TS_CLK_TX536_GPU_CCLK, GPU_CLK_CFG, 12, 5, 19) \
	DIV(TS_CLK_TX536_I2S0_OCLK, I2S_CLK_CFG, 0, 7, 7) \
	DIV(TS_CLK_TX536_I2S1_OCLK, I2S_CLK_CFG, 16, 7, 23) \
	DIV(TS_CLK_TX536_I2S0_MCLK, I2S_CLK_CFG, 8, 4, 12) \
	DIV(TS_CLK_TX536_I2S1_MCLK, I2S_CLK_CFG, 24, 4, 28) \
	DIV(TS_CLK_TX536_I2C_2_ICCLK, I2C_ICCLK_CFG0, 4, 4, 8) \
	DIV(TS_CLK_TX536_I2C_3_ICCLK, I2C_ICCLK_CFG0, 20, 4, 24) \
	DIV(TS_CLK_TX536_I2C_4_ICCLK, I2C_ICCLK_CFG1, 4, 4, 8) \
	DIV(TS_CLK_TX536_I2C_5_ICCLK, I2C_ICCLK_CFG1, 20, 4, 24) \
	DIV(TS_CLK_TX536_I2C_6_ICCLK, I2C_ICCLK_CFG2, 4, 4, 8) \
	DIV(TS_CLK_TX536_I2C_7_ICCLK, I2C_ICCLK_CFG2, 20, 4, 24) \
	DIV(TS_CLK_TX536_I2C_8_ICCLK, I2C_ICCLK_CFG3, 4, 4, 8) \
	DIV(TS_CLK_TX536_I2C_9_ICCLK, I2C_ICCLK_CFG3, 20, 4, 24) \
	DIV(TS_CLK_TX536_UART_1_SCLK, UART1_SCLK_CFG, 0, 28, 28) \
	DIV(TS_CLK_TX536_UART_2_SCLK, UART2_SCLK_CFG, 0, 28, 28) \
	DIV(TS_CLK_TX536_UART_3_SCLK, UART3_SCLK_CFG, 0, 28, 28) \
	DIV(TS_CLK_TX536_UART_4_SCLK, UART4_SCLK_CFG, 0, 28, 28) \
	DIV(TS_CLK_TX536_UART_5_SCLK, UART5_SCLK_CFG, 0, 28, 28) \
	DIV(TS_CLK_TX536_UART_6_SCLK, UART6_SCLK_CFG, 0, 28, 28) \
	DIV(TS_CLK_TX536_SPI_0_SSICLK, SPI_SCLK_CFG0, 4, 4, 8) \
	DIV(TS_CLK_TX536_SPI_1_SSICLK, SPI_SCLK_CFG0, 20, 4, 24) \
	DIV(TS_CLK_TX536_SPI_2_SSICLK, SPI_SCLK_CFG1, 4, 4, 8) \
	DIV(TS_CLK_TX536_SPI_3_SSICLK, SPI_SCLK_CFG1, 20, 4, 24) \
	DIV(TS_CLK_TX536_SPI_4_SSICLK, SPI_SCLK_CFG2, 4, 4, 8) \
	DIV(TS_CLK_TX536_TOP_TMR_T5CLK, TOP_TMR_TCK_CFG, 0, 5, 7) \
	DIV(TS_CLK_TX536_TOP_TMR_T6CLK, TOP_TMR_TCK_CFG, 8, 6, 15) \
	DIV(TS_CLK_TX536_TOP_TMR_T7CLK, TOP_TMR_TCK_CFG, 16, 6, 23) \
	DIV(TS_CLK_TX536_TOP_TMR_T8CLK, TOP_TMR_TCK_CFG, 24, 6, 31) \
	DIV(TS_CLK_TX536_SEC_TMR_T2CLK, SEC_TMR_TCK_CFG, 0, 5, 7) \
	DIV(TS_CLK_TX536_SEC_TMR_T3CLK, SEC_TMR_TCK_CFG, 8, 6, 15) \
	DIV(TS_CLK_TX536_VO_BUS_CLK, VO_BUS_CLK_CFG, 0, 3, 3) \
	DIV(TS_CLK_TX536_DP650_ACLK, DP650_CLK_CFG, 0, 4, 4) \
	DIV(TS_CLK_TX536_DMA2MIPI_ACLK, DMA2MIPI_CLK_CFG, 0, 4, 4) \
	DIV(TS_CLK_TX536_NEMADC_HCLK, NEMADC_CLK_CFG, 0, 4, 4) \
	DIV(TS_CLK_TX536_HDMI_TX_HCLK, HDMI_TX_CLK_CFG, 0, 4, 4) \
	DIV(TS_CLK_TX536_NEMADC_CCLK, NEMADC_CLK_CFG, 8, 6, 15) \
	DIV(TS_CLK_TX536_DMA2MIPI_CCLK, DMA2MIPI_CLK_CFG, 8, 6, 15) \
	DIV(TS_CLK_TX536_DP650_MCLK, DP650_CLK_CFG, 8, 6, 15) \
	DIV(TS_CLK_TX536_DP650_PXL_CLK, DP650_CLK_CFG, 16, 6, 23) \
	DIV(TS_CLK_TX536_MCTL_P0_ACLK, DDR_CTL_CLK_CFG0, 0, 4, 4) \
	DIV(TS_CLK_TX536_MCTL_P1_ACLK, DDR_CTL_CLK_CFG0, 8, 4, 12) \
	DIV(TS_CLK_TX536_MCTL_P2_ACLK, DDR_CTL_CLK_CFG0, 16, 4, 20) \
	DIV(TS_CLK_TX536_MCTL_P3_ACLK, DDR_CTL_CLK_CFG0, 24, 4, 28) \
	DIV(TS_CLK_TX536_MCTL_P4_ACLK, DDR_CTL_CLK_CFG1, 0, 4, 4) \
	DIV(TS_CLK_TX536_MCTL_P5_ACLK, DDR_CTL_CLK_CFG1, 8, 4, 12) \
	DIV(TS_CLK_TX536_VI_BUS_PCLK, VI_BUS_CLK_CFG, 0, 2, 3) \
	DIV(TS_CLK_TX536_ISP_ACLK, ISP_CLK_CFG, 0, 3, 3) \
	DIV(TS_CLK_TX536_ISP_SCLK, ISP_CLK_CFG, 8, 3, 11) \
	DIV(TS_CLK_TX536_VPE_ACLK, VPE_CLK_CFG, 0, 5, 7) \
	DIV(TS_CLK_TX536_VPE_CCLK, VPE_CLK_CFG, 8, 4, 12) \
	DIV(TS_CLK_TX536_WAVE_ACLK, VPU_BUS_CLK_CFG, 0, 3, 3) \
	DIV(TS_CLK_TX536_CODA_ACLK, VPU_BUS_CLK_CFG, 8, 3, 11) \
	DIV(TS_CLK_TX536_VPU_CFG_PCLK, VPU_BUS_CLK_CFG, 16, 3, 19) \
	DIV(TS_CLK_TX536_WAVE_CCLK, WAVE_FUNC_CLK_CFG, 0, 4, 4) \
	DIV(TS_CLK_TX536_WAVE_BCLK, WAVE_FUNC_CLK_CFG, 8, 3, 11) \
	DIV(TS_CLK_TX536_CODA_CCLK, CODA_FUNC_CLK_CFG, 0, 4, 4) \
	DIV(TS_CLK_TX536_AISYS_HCLK, AI_BUS_CLK_CFG, 0, 3, 4) \
	DIV(TS_CLK_TX536_RNE_ACLK, AI_BUS_CLK_CFG, 8, 5, 15) \
	DIV(TS_CLK_TX536_RCE_ACLK, AI_BUS_CLK_CFG, 16, 5, 23) \
	DIV(TS_CLK_TX536_AI_MEM_ACLK, AI_BUS_CLK_CFG, 24, 4, 28) \
	DIV(TS_CLK_TX536_RCE_CCLK, RCE_CCLK_CFG, 0, 4, 4) \
	DIV(TS_CLK_TX536_RNE_CCLK, RNE_CCLK_CFG, 0, 5, 7) \
	DIV(TS_CLK_TX536_MCU_NOC_CLK, MCU_BUS_CLK_CFG0, 4, 4, 8) \
	DIV(TS_CLK_TX536_MCU_BUS_PCLK, MCU_BUS_CLK_CFG1, 0, 3, 3) \
	DIV(TS_CLK_TX536_MCU_DDR_ACLK, MCU_BUS_CLK_CFG2, 0, 2, 3) \
	DIV(TS_CLK_TX536_DVP_ACLK, DVP_CLK_CFG, 0, 3, 3) \
	DIV(TS_CLK_TX536_DVP_MCLK, DVP_CLK_CFG, 8, 3, 11) \
	DIV(TS_CLK_TX536_UART_0_SCLK, UART0_CLK_CFG, 0, 28, 28) \
	DIV(TS_CLK_TX536_I2C_0_ICCLK, I2C0_CLK_CFG, 0, 5, 7) \
	DIV(TS_CLK_TX536_I2C_1_ICCLK, I2C1_CLK_CFG, 0, 5, 7) \
	DIV(TS_CLK_TX536_TMR_T2CLK, MCU_TMR_CLK_CFG, 0, 6, 7) \
	DIV(TS_CLK_TX536_TMR_T3CLK, MCU_TMR_CLK_CFG, 8, 6, 15) \
	DIV(TS_CLK_TX536_TMR_T4CLK, MCU_TMR_CLK_CFG, 16, 6, 23)

#define _DIVIFY(id) TS_CLK_TX536_DIV_##id
#define DIVIFY(id) _DIVIFY(id)

enum ts_div_ids {
#define DIV_FLAGS(id, ...) DIVIFY(id),
	DIV_LIST
#undef DIV_FLAGS
	TS_CLK_DIV_NONE,
};

static const struct ts_div_params ts_tx536_divs[] = {
#define DIV_FLAGS(id, _off, _shift, _width, _we, _sync, _flags) \
	[DIVIFY(id)] = { \
		.off = (_off), \
		.shift = (_shift), \
		.width = (_width), \
		.we = (_we), \
		.sync = (_sync), \
		.flags = (_flags), \
	},
	DIV_LIST
#undef DIV_FLAGS
};

#undef DIV
#undef DIV_LIST

#define GATE_LIST \
	GATE(TS_CLK_TX536_CX400_DAP_CLK, CX400_CLK_EN,  0) \
	GATE(TS_CLK_TX536_CX400_ATCLK, CX400_CLK_EN,  1) \
	GATE(TS_CLK_TX536_CX400_TSCLK, CX400_CLK_EN,  2) \
	GATE(TS_CLK_TX536_CX400_TRACE_CLK, CX400_CLK_EN,  3) \
	GATE(TS_CLK_TX536_CX400_DP_CLK, CX400_CLK_EN,  4) \
	GATE(TS_CLK_TX536_DMAC_0_ACLK, TOP_BUS_CLK_EN0,  0) \
	GATE(TS_CLK_TX536_DMAC_1_ACLK, TOP_BUS_CLK_EN0,  4) \
	GATE(TS_CLK_TX536_BOOTROM_HCLK, TOP_BUS_CLK_EN0,  5) \
	GATE(TS_CLK_TX536_MSHC_0_HCLK, TOP_BUS_CLK_EN0,  6) \
	GATE(TS_CLK_TX536_MSHC_1_HCLK, TOP_BUS_CLK_EN0,  7) \
	GATE(TS_CLK_TX536_GMAC_BUS_CLK, TOP_BUS_CLK_EN0,  8) \
	GATE(TS_CLK_TX536_MMU_ACLK, TOP_BUS_CLK_EN0,  9) \
	GATE(TS_CLK_TX536_GIC400_ACLK, TOP_BUS_CLK_EN0,  10) \
	GATE(TS_CLK_TX536_CRYPTO_BUS_CLK, TOP_BUS_CLK_EN0,  12) \
	GATE(TS_CLK_TX536_USB3C_BUS_CLK, TOP_BUS_CLK_EN0,  13) \
	GATE(TS_CLK_TX536_BT1120_TX_BUS_CLK, TOP_BUS_CLK_EN1,  0) \
	GATE(TS_CLK_TX536_BT1120_RX_BUS_CLK, TOP_BUS_CLK_EN1,  1) \
	GATE(TS_CLK_TX536_OSPI_BUS_CLK, TOP_BUS_CLK_EN1,  2) \
	GATE(TS_CLK_TX536_NFC_HCLK, TOP_BUS_CLK_EN1,  3) \
	GATE(TS_CLK_TX536_GDC_ACLK, TOP_BUS_CLK_EN1,  4) \
	GATE(TS_CLK_TX536_GDC_PCLK, TOP_BUS_CLK_EN1,  5) \
	GATE(TS_CLK_TX536_CVE_ACLK, TOP_BUS_CLK_EN1,  6) \
	GATE(TS_CLK_TX536_CVE_HCLK, TOP_BUS_CLK_EN1,  7) \
	GATE(TS_CLK_TX536_GPU_ACLK, TOP_BUS_CLK_EN1,  8) \
	GATE(TS_CLK_TX536_GPU_PCLK, TOP_BUS_CLK_EN1,  9) \
	GATE(TS_CLK_TX536_TOP_WDT_PCLK, TOP_BUS_CLK_EN2,  0) \
	GATE(TS_CLK_TX536_SEC_WDT_PCLK, TOP_BUS_CLK_EN2,  1) \
	GATE(TS_CLK_TX536_TOP_TMR_PCLK, TOP_BUS_CLK_EN2,  2) \
	GATE(TS_CLK_TX536_SEC_TMR_PCLK, TOP_BUS_CLK_EN2,  3) \
	GATE(TS_CLK_TX536_TOP_GPIO_PCLK, TOP_BUS_CLK_EN2,  4) \
	GATE(TS_CLK_TX536_OTPC_PCLK, TOP_BUS_CLK_EN2,  6) \
	GATE(TS_CLK_TX536_ADC_PCLK, TOP_BUS_CLK_EN2,  7) \
	GATE(TS_CLK_TX536_TOP_PADC_PCLK, TOP_BUS_CLK_EN2,  8) \
	GATE(TS_CLK_TX536_MAILBOX_PCLK, TOP_BUS_CLK_EN2,  9) \
	GATE(TS_CLK_TX536_SPI_0_PCLK, TOP_BUS_CLK_EN3,  0) \
	GATE(TS_CLK_TX536_SPI_1_PCLK, TOP_BUS_CLK_EN3,  1) \
	GATE(TS_CLK_TX536_SPI_2_PCLK, TOP_BUS_CLK_EN3,  2) \
	GATE(TS_CLK_TX536_SPI_3_PCLK, TOP_BUS_CLK_EN3,  3) \
	GATE(TS_CLK_TX536_SPI_4_PCLK, TOP_BUS_CLK_EN3,  4) \
	GATE(TS_CLK_TX536_I2S_0_PCLK, TOP_BUS_CLK_EN3,  5) \
	GATE(TS_CLK_TX536_I2S_1_PCLK, TOP_BUS_CLK_EN3,  6) \
	GATE(TS_CLK_TX536_UART_1_PCLK, TOP_BUS_CLK_EN4,  0) \
	GATE(TS_CLK_TX536_UART_2_PCLK, TOP_BUS_CLK_EN4,  1) \
	GATE(TS_CLK_TX536_UART_3_PCLK, TOP_BUS_CLK_EN4,  2) \
	GATE(TS_CLK_TX536_UART_4_PCLK, TOP_BUS_CLK_EN4,  3) \
	GATE(TS_CLK_TX536_UART_5_PCLK, TOP_BUS_CLK_EN4,  4) \
	GATE(TS_CLK_TX536_UART_6_PCLK, TOP_BUS_CLK_EN4,  5) \
	GATE(TS_CLK_TX536_USI_2_PCLK, TOP_BUS_CLK_EN4,  6) \
	GATE(TS_CLK_TX536_USI_3_PCLK, TOP_BUS_CLK_EN4,  7) \
	GATE(TS_CLK_TX536_I2C_2_PCLK, TOP_BUS_CLK_EN5,  0) \
	GATE(TS_CLK_TX536_I2C_3_PCLK, TOP_BUS_CLK_EN5,  1) \
	GATE(TS_CLK_TX536_I2C_4_PCLK, TOP_BUS_CLK_EN5,  2) \
	GATE(TS_CLK_TX536_I2C_5_PCLK, TOP_BUS_CLK_EN5,  3) \
	GATE(TS_CLK_TX536_I2C_6_PCLK, TOP_BUS_CLK_EN5,  4) \
	GATE(TS_CLK_TX536_I2C_7_PCLK, TOP_BUS_CLK_EN5,  5) \
	GATE(TS_CLK_TX536_I2C_8_PCLK, TOP_BUS_CLK_EN5,  6) \
	GATE(TS_CLK_TX536_I2C_9_PCLK, TOP_BUS_CLK_EN5,  7) \
	GATE(TS_CLK_TX536_MSHC_0_BCLK, MSHC0_CCLK_CFG0,  20) \
	GATE(TS_CLK_TX536_MSHC_1_BCLK, MSHC1_CCLK_CFG0,  20) \
	GATE(TS_CLK_TX536_USB_PHY_REFCLK, USB3_FUNC_CLK_CFG, 3) \
	GATE(TS_CLK_TX536_USB_CTL_REFCLK, USB3_FUNC_CLK_CFG, 5) \
	GATE(TS_CLK_TX536_CVE_CCLK, CVE_CLK_CFG, 16) \
	GATE(TS_CLK_TX536_GPU_CCLK, GPU_CLK_CFG, 20) \
	GATE(TS_CLK_TX536_I2S0_OCLK, I2S_CLK_CFG, 14) \
	GATE(TS_CLK_TX536_I2S1_OCLK, I2S_CLK_CFG, 30) \
	GATE(TS_CLK_TX536_I2S0_MCLK, I2S_CLK_CFG, 15) \
	GATE(TS_CLK_TX536_I2S1_MCLK, I2S_CLK_CFG, 31) \
	GATE(TS_CLK_TX536_TOP_TMR_T3CLK, TOP_TMR_TCK_EN, 0) \
	GATE(TS_CLK_TX536_TOP_TMR_T4CLK, TOP_TMR_TCK_EN, 1) \
	GATE(TS_CLK_TX536_TOP_TMR_T5CLK, TOP_TMR_TCK_EN, 2) \
	GATE(TS_CLK_TX536_TOP_TMR_T6CLK, TOP_TMR_TCK_EN, 3) \
	GATE(TS_CLK_TX536_TOP_TMR_T7CLK, TOP_TMR_TCK_EN, 4) \
	GATE(TS_CLK_TX536_TOP_TMR_T8CLK, TOP_TMR_TCK_EN, 5) \
	GATE(TS_CLK_TX536_SEC_TMR_T2CLK, SEC_TMR_TCK_EN, 0) \
	GATE(TS_CLK_TX536_SEC_TMR_T3CLK, SEC_TMR_TCK_EN, 1) \
	GATE(TS_CLK_TX536_CHIP_OCLK_0, CHIP_OUT_CLK_CFG0, 12) \
	GATE(TS_CLK_TX536_CHIP_OCLK_1, CHIP_OUT_CLK_CFG0, 28) \
	GATE(TS_CLK_TX536_CHIP_OCLK_2, CHIP_OUT_CLK_CFG1, 12) \
	GATE(TS_CLK_TX536_CHIP_OCLK_3, CHIP_OUT_CLK_CFG1, 28) \
	GATE(TS_CLK_TX536_MII_RXCLK, GMAC_MAC_CLK_EN, 0) \
	GATE(TS_CLK_TX536_MII_TXCLK, GMAC_MAC_CLK_EN, 1) \
	GATE(TS_CLK_TX536_MAC_CLK_RMII, GMAC_MAC_CLK_EN, 4) \
	GATE(TS_CLK_TX536_RMII_TX_CLK, GMAC_MAC_CLK_EN, 5) \
	GATE(TS_CLK_TX536_GMII_TX_CLK, GMAC_MAC_CLK_EN, 6) \
	GATE(TS_CLK_TX536_PTP_REF_CLK, GMAC_MAC_CLK_EN, 8) \
	GATE(TS_CLK_TX536_EPHY_REF_CLK, GMAC_MAC_CLK_EN, 9) \
	GATE(TS_CLK_TX536_DP650_PCLK, VO_SYS_CLK_EN0, 0) \
	GATE(TS_CLK_TX536_DMA2MIPI_PCLK, VO_SYS_CLK_EN0, 1) \
	GATE(TS_CLK_TX536_CSI_DEV_PCLK, VO_SYS_CLK_EN0, 2) \
	GATE(TS_CLK_TX536_DSI_HOST_PCLK, VO_SYS_CLK_EN0, 3) \
	GATE(TS_CLK_TX536_HDMI_TX_PCLK, VO_SYS_CLK_EN0, 4) \
	GATE(TS_CLK_TX536_VO_BUS_CLK, VO_SYS_CLK_EN0, 8) \
	GATE(TS_CLK_TX536_DP650_ACLK, VO_SYS_CLK_EN0, 12) \
	GATE(TS_CLK_TX536_DMA2MIPI_ACLK, VO_SYS_CLK_EN0, 13) \
	GATE(TS_CLK_TX536_NEMADC_HCLK, VO_SYS_CLK_EN0, 14) \
	GATE(TS_CLK_TX536_HDMI_TX_HCLK, VO_SYS_CLK_EN0, 15) \
	GATE(TS_CLK_TX536_NEMADC_CCLK, VO_SYS_CLK_EN1, 0) \
	GATE(TS_CLK_TX536_DMA2MIPI_CCLK, VO_SYS_CLK_EN1, 1) \
	GATE(TS_CLK_TX536_DP650_MCLK, VO_SYS_CLK_EN1, 3) \
	GATE(TS_CLK_TX536_DP650_PXL_CLK, VO_SYS_CLK_EN1, 4) \
	GATE(TS_CLK_TX536_DSI_HOST_IPI_CLK, VO_SYS_CLK_EN1, 5) \
	GATE(TS_CLK_TX536_MIPI_TXPHY_REF_CLK, VO_SYS_CLK_EN1, 6) \
	GATE(TS_CLK_TX536_MIPI_TXPHY_CFG_CLK, VO_SYS_CLK_EN1, 7) \
	GATE(TS_CLK_TX536_HDMI_TX_PXL_CLK, VO_SYS_CLK_EN1, 8) \
	GATE(TS_CLK_TX536_HDMI_TX_CFG_CLK, VO_SYS_CLK_EN1, 9) \
	GATE(TS_CLK_TX536_MCTL_P0_ACLK, DDR_CTL_CLK_EN, 0) \
	GATE(TS_CLK_TX536_MCTL_P1_ACLK, DDR_CTL_CLK_EN, 1) \
	GATE(TS_CLK_TX536_MCTL_P2_ACLK, DDR_CTL_CLK_EN, 2) \
	GATE(TS_CLK_TX536_MCTL_P3_ACLK, DDR_CTL_CLK_EN, 3) \
	GATE(TS_CLK_TX536_MCTL_P4_ACLK, DDR_CTL_CLK_EN, 4) \
	GATE(TS_CLK_TX536_MCTL_P5_ACLK, DDR_CTL_CLK_EN, 5) \
	GATE(TS_CLK_TX536_MCTL_PCLK, DDR_CTL_CLK_EN, 8) \
	GATE(TS_CLK_TX536_MCTL_DDRC_CLK, DDR_CTL_CLK_EN, 12) \
	GATE(TS_CLK_TX536_CSI_HOST_0_PCLK, VI_BUS_CLK_EN, 0) \
	GATE(TS_CLK_TX536_CSI_HOST_1_PCLK, VI_BUS_CLK_EN, 1) \
	GATE(TS_CLK_TX536_CSI_HOST_2_PCLK, VI_BUS_CLK_EN, 2) \
	GATE(TS_CLK_TX536_VPE_PCLK, VI_BUS_CLK_EN, 3) \
	GATE(TS_CLK_TX536_HDR_PCLK, VI_BUS_CLK_EN, 4) \
	GATE(TS_CLK_TX536_TNR_HCLK, VI_BUS_CLK_EN, 5) \
	GATE(TS_CLK_TX536_ISP_ACLK, VI_BUS_CLK_EN, 8) \
	GATE(TS_CLK_TX536_HDR_ACLK, VI_BUS_CLK_EN, 9) \
	GATE(TS_CLK_TX536_VPE_ACLK, VI_BUS_CLK_EN, 10) \
	GATE(TS_CLK_TX536_TNR_ACLK, VI_BUS_CLK_EN, 11) \
	GATE(TS_CLK_TX536_VI_BUS_PCLK, VI_BUS_CLK_EN, 12) \
	GATE(TS_CLK_TX536_CSI_HOST_0_PXLCLK0, VI_FUNC_CLK_EN0, 0) \
	GATE(TS_CLK_TX536_CSI_HOST_0_PXLCLK1, VI_FUNC_CLK_EN0, 1) \
	GATE(TS_CLK_TX536_CSI_HOST_0_PXLCLK2, VI_FUNC_CLK_EN0, 2) \
	GATE(TS_CLK_TX536_CSI_HOST_1_PXLCLK0, VI_FUNC_CLK_EN0, 4) \
	GATE(TS_CLK_TX536_CSI_HOST_2_PXLCLK0, VI_FUNC_CLK_EN0, 5) \
	GATE(TS_CLK_TX536_ISP_SCLK, VI_FUNC_CLK_EN0, 8) \
	GATE(TS_CLK_TX536_TNR_CCLK, VI_FUNC_CLK_EN0, 9) \
	GATE(TS_CLK_TX536_VPE_CCLK, VI_FUNC_CLK_EN0, 10) \
	GATE(TS_CLK_TX536_MIPI_RXPHY0_CFGCLK, VI_FUNC_CLK_EN1, 0) \
	GATE(TS_CLK_TX536_MIPI_RXPHY1_CFGCLK, VI_FUNC_CLK_EN1, 1) \
	GATE(TS_CLK_TX536_MIPI_RXPHY2_CFGCLK, VI_FUNC_CLK_EN1, 2) \
	GATE(TS_CLK_TX536_WAVE_ACLK, VPU_BUS_CLK_EN, 0) \
	GATE(TS_CLK_TX536_CODA_ACLK, VPU_BUS_CLK_EN, 1) \
	GATE(TS_CLK_TX536_WAVE_PCLK, VPU_BUS_CLK_EN, 4) \
	GATE(TS_CLK_TX536_CODA_PCLK, VPU_BUS_CLK_EN, 5) \
	GATE(TS_CLK_TX536_VPU_CFG_PCLK, VPU_BUS_CLK_EN, 6) \
	GATE(TS_CLK_TX536_WAVE_CCLK, WAVE_FUNC_CLK_CFG, 12) \
	GATE(TS_CLK_TX536_WAVE_BCLK, WAVE_FUNC_CLK_CFG, 13) \
	GATE(TS_CLK_TX536_CODA_CCLK, CODA_FUNC_CLK_CFG, 8) \
	GATE(TS_CLK_TX536_RNE_HCLK, AI_BUS_CLK_EN, 0) \
	GATE(TS_CLK_TX536_RNE_ACLK, AI_BUS_CLK_EN, 1) \
	GATE(TS_CLK_TX536_RCE_HCLK, AI_BUS_CLK_EN, 4) \
	GATE(TS_CLK_TX536_RCE_ACLK, AI_BUS_CLK_EN, 5) \
	GATE(TS_CLK_TX536_AI_ISP_HCLK, AI_BUS_CLK_EN, 8) \
	GATE(TS_CLK_TX536_AI_MEM_ACLK, AI_BUS_CLK_EN, 9) \
	GATE(TS_CLK_TX536_RCE_CCLK, RCE_CCLK_CFG, 5) \
	GATE(TS_CLK_TX536_RNE_CCLK, RNE_CCLK_CFG, 8) \
	GATE(TS_CLK_TX536_MCU_DDR_ACLK, MCU_BUS_CLK_EN1, 3) \
	GATE(TS_CLK_TX536_PWM_PCLK, MCU_BUS_CLK_EN0, 0) \
	GATE(TS_CLK_TX536_MCU_PADC_PCLK, MCU_BUS_CLK_EN0, 1) \
	GATE(TS_CLK_TX536_MCU_TMR_PCLK, MCU_BUS_CLK_EN0, 2) \
	GATE(TS_CLK_TX536_MCU_WDT_PCLK, MCU_BUS_CLK_EN0, 3) \
	GATE(TS_CLK_TX536_UART_0_PCLK, MCU_BUS_CLK_EN0, 4) \
	GATE(TS_CLK_TX536_I2C_0_PCLK, MCU_BUS_CLK_EN0, 5) \
	GATE(TS_CLK_TX536_I2C_1_PCLK, MCU_BUS_CLK_EN0, 6) \
	GATE(TS_CLK_TX536_USI_0_PCLK, MCU_BUS_CLK_EN0, 7) \
	GATE(TS_CLK_TX536_USI_1_PCLK, MCU_BUS_CLK_EN0, 8) \
	GATE(TS_CLK_TX536_MCU_GPIO_PCLK, MCU_BUS_CLK_EN0, 9) \
	GATE(TS_CLK_TX536_MCU_RAM_ACLK, MCU_BUS_CLK_EN1, 0) \
	GATE(TS_CLK_TX536_DVP_PCLK, MCU_BUS_CLK_EN1, 1) \
	GATE(TS_CLK_TX536_DVP_ACLK, MCU_BUS_CLK_EN1, 2) \
	GATE(TS_CLK_TX536_SYS_REG_PCLK, MCU_BUS_CLK_EN1, 4) \
	GATE(TS_CLK_TX536_MCU_RNE_ACLK, MCU_BUS_CLK_EN1, 5) \
	GATE(TS_CLK_TX536_DMAC2_HCLK, MCU_BUS_CLK_EN1, 6) \
	GATE(TS_CLK_TX536_AUDIO_HCLK, MCU_BUS_CLK_EN1, 7) \
	GATE(TS_CLK_TX536_AUDIO_PCLK, MCU_BUS_CLK_EN1, 8) \
	GATE(TS_CLK_TX536_DVP_MCLK, DVP_CLK_CFG, 16) \
	GATE(TS_CLK_TX536_AUDIO_MCLK, AUD_CLK_CFG, 4) \
	GATE(TS_CLK_TX536_TMR_T2CLK, MCU_TMR_CLK_EN, 0) \
	GATE(TS_CLK_TX536_TMR_T3CLK, MCU_TMR_CLK_EN, 1) \
	GATE(TS_CLK_TX536_TMR_T4CLK, MCU_TMR_CLK_EN, 2) \
	GATE(TS_CLK_TX536_MCU_CLK24M, MCU_CLK24M_EN, 0) \
	GATE(TS_CLK_TX536_CHIP_OCLK_4, CHIP_OCLK4_CFG, 12)

#define _GATEIFY(id) TS_CLK_TX536_GATE_##id
#define GATEIFY(id) _GATEIFY(id)

enum ts_gate_ids {
#define GATE(id, ...) GATEIFY(id),
	GATE_LIST
#undef GATE
	TS_CLK_GATE_NONE,
};

static const struct ts_gate_params ts_tx536_gates[] = {
#define GATE(id, _off, _idx) \
	[GATEIFY(id)] = { \
		.off = (_off), \
		.bit_idx = (_idx), \
	},
	GATE_LIST
#undef GATE
};

#undef GATE_LIST

#define MUX(id, reg, shift, width, we, sync) \
	MUX_PARENTS(id, generic_sels, reg, shift, width, we, sync)
#define MUX_LIST \
	MUX_PARENTS(TS_CLK_TX536_A53_CLKIN, a53_clkin_sels, A53_CLK_CFG0, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_CX400_ATCLK, cx400_clk_sels, CX400_CLK_CFG, 8, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_CX400_DAP_CLK, cx400_clk_sels, CX400_CLK_CFG, 8, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_CX400_DP_CLK, cx400_clk_sels, CX400_CLK_CFG, 8, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_TOP_NOC_CLK, top_noc_clk_sels, TOP_NOC_CLK_CFG, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_MSHC_0_HCLK, mshc_hclk_sels, MSHC_BUS_CLK_CFG, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_MSHC_1_HCLK, mshc_hclk_sels, MSHC_BUS_CLK_CFG, 16, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_CRYPTO_BUS_CLK, crypto_bus_clk_sels, CRYPTO_BUS_CLK_CFG, 4, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_USB3C_BUS_CLK, usb3c_bus_clk_sels, USB3_BUS_CLK_CFG, 4, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_GDC_ACLK, gdc_aclk_sels, GDC_CLK_CFG, 5, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_CVE_ACLK, cve_aclk_sels, CVE_CLK_CFG, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_GPU_ACLK, gpu_aclk_sels, GPU_CLK_CFG, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_GMAC_ACLK, gmac_aclk_sels, GMAC_ACLK_CFG, 4, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_MSHC_0_BCLK, mshc_bclk_sels, MSHC0_CCLK_CFG0, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_MSHC_1_BCLK, mshc_bclk_sels, MSHC1_CCLK_CFG0, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_USB_PHY_REFCLK, usb_phy_refclk_sels, USB3_FUNC_CLK_CFG, 0, 2, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_USB_CTL_REFCLK, usb_ctl_refclk_sels, USB3_FUNC_CLK_CFG, 4, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_NFC_CLKB, nfc_clkb_sels, NFC_CLKB_CFG, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_BT1120TX_ACLK, bt1120_aclk_sels, BT1120_CLK_CFG, 4, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_BT1120RX_ACLK, bt1120_aclk_sels, BT1120_CLK_CFG, 12, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_OSPI_HCLK, ospi_hclk_sels, OSPI_HCLK_CFG, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_OSPI_REF_CLK, ospi_ref_clk_sels, OSPI_REF_CLK_CFG, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_2_ICCLK, i2c_2_9_icclk_sels, I2C_ICCLK_CFG0, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_3_ICCLK, i2c_2_9_icclk_sels, I2C_ICCLK_CFG0, 16, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_4_ICCLK, i2c_2_9_icclk_sels, I2C_ICCLK_CFG1, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_5_ICCLK, i2c_2_9_icclk_sels, I2C_ICCLK_CFG1, 16, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_6_ICCLK, i2c_2_9_icclk_sels, I2C_ICCLK_CFG2, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_7_ICCLK, i2c_2_9_icclk_sels, I2C_ICCLK_CFG2, 16, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_8_ICCLK, i2c_2_9_icclk_sels, I2C_ICCLK_CFG3, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_9_ICCLK, i2c_2_9_icclk_sels, I2C_ICCLK_CFG3, 16, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_UART_1_SCLK, uart_1_6_sclk_sels, UART1_SCLK_CFG, 31, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_UART_2_SCLK, uart_1_6_sclk_sels, UART2_SCLK_CFG, 31, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_UART_3_SCLK, uart_1_6_sclk_sels, UART3_SCLK_CFG, 31, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_UART_4_SCLK, uart_1_6_sclk_sels, UART4_SCLK_CFG, 31, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_UART_5_SCLK, uart_1_6_sclk_sels, UART5_SCLK_CFG, 31, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_UART_6_SCLK, uart_1_6_sclk_sels, UART6_SCLK_CFG, 31, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_SPI_0_SSICLK, spi_ssiclk_sels, SPI_SCLK_CFG0, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_SPI_1_SSICLK, spi_ssiclk_sels, SPI_SCLK_CFG0, 16, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_SPI_2_SSICLK, spi_ssiclk_sels, SPI_SCLK_CFG1, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_SPI_3_SSICLK, spi_ssiclk_sels, SPI_SCLK_CFG1, 16, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_SPI_4_SSICLK, spi_ssiclk_sels, SPI_SCLK_CFG2, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_CHIP_OCLK_0, chip_out_clk_sels, CHIP_OUT_CLK_CFG0, 0, 4, 4, 8) \
	MUX_PARENTS(TS_CLK_TX536_CHIP_OCLK_1, chip_out_clk_sels, CHIP_OUT_CLK_CFG0, 16, 4, 20, 24) \
	MUX_PARENTS(TS_CLK_TX536_CHIP_OCLK_2, chip_out_clk_sels, CHIP_OUT_CLK_CFG1, 0, 4, 4, 8) \
	MUX_PARENTS(TS_CLK_TX536_CHIP_OCLK_3, chip_out_clk_sels, CHIP_OUT_CLK_CFG1, 16, 4, 20, 24) \
	MUX_PARENTS(TS_CLK_TX536_MIPI_TXPHY_REF_CLK, dma2mipi_txphy_clk_sels, DMA2MIPI_CLK_CFG, 16, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_MIPI_TXPHY_CFG_CLK, dma2mipi_txphy_clk_sels, DMA2MIPI_CLK_CFG, 16, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_ISP_SCLK, isp_sclk_sels, ISP_CLK_CFG, 12, 2, WE_INVALID, 15) \
	MUX_PARENTS(TS_CLK_TX536_MIPI_RXPHY0_CFGCLK, mipi_rxphy_cfgclk_sels, VI_FUNC_CLK_EN1, 4, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_MIPI_RXPHY1_CFGCLK, mipi_rxphy_cfgclk_sels, VI_FUNC_CLK_EN1, 4, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_MIPI_RXPHY2_CFGCLK, mipi_rxphy_cfgclk_sels, VI_FUNC_CLK_EN1, 4, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_AI_MEM_ACLK, ai_mem_aclk_sels, AI_BUS_CLK_CFG, 29, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_MCU_NOC_CLK, mcu_noc_clk_sels, MCU_BUS_CLK_CFG0, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_MCU_DDR_ACLK, mcu_ddr_aclk_sels, MCU_BUS_CLK_CFG2, 4, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_AUDIO_PCLK, aud_pclk_sels, AUD_CLK_CFG, 8, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_AUDIO_MCLK, aud_mclk_sels, AUD_CLK_CFG, 0, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_UART_0_SCLK, uart0_sclk_sels, UART0_CLK_CFG, 31, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_0_ICCLK, i2c_0_1_icclk_sels, I2C0_CLK_CFG, 31, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_I2C_1_ICCLK, i2c_0_1_icclk_sels, I2C1_CLK_CFG, 31, 1, WE_INVALID, SYNC_INVALID) \
	MUX_PARENTS(TS_CLK_TX536_CHIP_OCLK_4, chip_out_clk_sels, CHIP_OCLK4_CFG, 0, 4, 4, 8)

#define _MUXIFY(id) TS_CLK_TX536_MUX_##id
#define MUXIFY(id) _MUXIFY(id)

enum ts_mux_ids {
#define MUX_PARENTS(id, ...) MUXIFY(id),
	MUX_LIST
#undef MUX_PARENTS
	TS_CLK_MUX_NONE,
};


static const struct ts_mux_params ts_tx536_muxes[] = {
#define MUX_PARENTS(id, parents, _off, _shift, _width, _we, _sync) \
	[MUXIFY(id)] = { \
		.parent_names = (const char * const *)(parents), \
		.num_parents = ARRAY_SIZE(parents), \
		.off = (_off), \
		.shift = (_shift), \
		.width = (_width), \
		.we = (_we), \
		.sync = (_sync), \
	},
	MUX_LIST
#undef MUX_PARENTS
};

#undef MUX
#undef MUX_LIST


static struct ts_pll_params ts_tx536_plls[] = {
#define PLL(_name, _id, _off, _shift, _width) { \
	.name = _name, \
	.id = _id, \
	.off = (_off), \
	.lock_off = PLL_STATUS, \
	.shift = (_shift), \
	.width = (_width), \
}
	[0] = PLL("cpu_pll",  TS_CLK_TX536_CPU_PLL,  CPU_PLL_CFG0,  0, 1),
	[1] = PLL("bus_pll",  TS_CLK_TX536_BUS_PLL,  BUS_PLL_CFG0,  1, 1),
	[2] = PLL("ddr_pll",  TS_CLK_TX536_DDR_PLL,  DDR_PLL_CFG0,  2, 1),
	[3] = PLL("disp_pll", TS_CLK_TX536_DISP_PLL, DISP_PLL_CFG0, 3, 1),
	[4] = PLL("aud_pll",  TS_CLK_TX536_AUD_PLL,  AUD_PLL_CFG0,  4, 1),
	[5] = PLL("ai_pll",   TS_CLK_TX536_AI_PLL,   AI_PLL_CFG0,   5, 1),
	[6] = PLL("mcu_pll",  TS_CLK_TX536_MCU_PLL,  MCU_PLL_CFG0,  0, 1),
#undef PLL
};

#define COMP(id) \
	COMP_FULL(id, MUXIFY(id), DIVIFY(id), GATEIFY(id))
#define COMP_NOMUX(id) \
	COMP_FULL(id, TS_CLK_MUX_NONE, DIVIFY(id), GATEIFY(id))
#define COMP_NOGATE(id) \
	COMP_FULL(id, MUXIFY(id), DIVIFY(id), TS_CLK_GATE_NONE)
#define COMP_NODIV(id) \
	COMP_FULL(id, MUXIFY(id), TS_CLK_DIV_NONE, GATEIFY(id))
#define COMP_DIV_ONLY(id) \
	COMP_FULL(id, TS_CLK_MUX_NONE, DIVIFY(id), TS_CLK_GATE_NONE)
#define COMP_GATE_ONLY(id) \
	COMP_FULL(id, TS_CLK_MUX_NONE, TS_CLK_DIV_NONE, GATEIFY(id))
#define COMP_LIST \
	COMP_NOGATE(TS_CLK_TX536_A53_CLKIN) \
	COMP(TS_CLK_TX536_CX400_ATCLK) \
	COMP(TS_CLK_TX536_CX400_DAP_CLK) \
	COMP_NODIV(TS_CLK_TX536_CX400_DP_CLK) \
	COMP_NOGATE(TS_CLK_TX536_TOP_NOC_CLK) \
	COMP(TS_CLK_TX536_MSHC_0_HCLK) \
	COMP(TS_CLK_TX536_MSHC_1_HCLK) \
	COMP(TS_CLK_TX536_CRYPTO_BUS_CLK) \
	COMP(TS_CLK_TX536_USB3C_BUS_CLK) \
	COMP(TS_CLK_TX536_GDC_ACLK) \
	COMP(TS_CLK_TX536_CVE_ACLK) \
	COMP(TS_CLK_TX536_GPU_ACLK) \
	COMP_NOGATE(TS_CLK_TX536_GMAC_ACLK) \
	COMP(TS_CLK_TX536_MSHC_0_BCLK) \
	COMP(TS_CLK_TX536_MSHC_1_BCLK) \
	COMP_NODIV(TS_CLK_TX536_USB_PHY_REFCLK) \
	COMP_NODIV(TS_CLK_TX536_USB_CTL_REFCLK) \
	COMP_NOGATE(TS_CLK_TX536_NFC_CLKB) \
	COMP_NOGATE(TS_CLK_TX536_BT1120TX_ACLK) \
	COMP_NOGATE(TS_CLK_TX536_BT1120RX_ACLK) \
	COMP_NOGATE(TS_CLK_TX536_OSPI_HCLK) \
	COMP_NOGATE(TS_CLK_TX536_OSPI_REF_CLK) \
	COMP_NOMUX(TS_CLK_TX536_CVE_CCLK) \
	COMP_NOMUX(TS_CLK_TX536_GPU_CCLK) \
	COMP_NOMUX(TS_CLK_TX536_I2S0_OCLK) \
	COMP_NOMUX(TS_CLK_TX536_I2S1_OCLK) \
	COMP_NOMUX(TS_CLK_TX536_I2S0_MCLK) \
	COMP_NOMUX(TS_CLK_TX536_I2S1_MCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_2_ICCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_3_ICCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_4_ICCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_5_ICCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_6_ICCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_7_ICCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_8_ICCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_9_ICCLK) \
	COMP_NOGATE(TS_CLK_TX536_UART_1_SCLK) \
	COMP_NOGATE(TS_CLK_TX536_UART_2_SCLK) \
	COMP_NOGATE(TS_CLK_TX536_UART_3_SCLK) \
	COMP_NOGATE(TS_CLK_TX536_UART_4_SCLK) \
	COMP_NOGATE(TS_CLK_TX536_UART_5_SCLK) \
	COMP_NOGATE(TS_CLK_TX536_UART_6_SCLK) \
	COMP_NOGATE(TS_CLK_TX536_SPI_0_SSICLK) \
	COMP_NOGATE(TS_CLK_TX536_SPI_1_SSICLK) \
	COMP_NOGATE(TS_CLK_TX536_SPI_2_SSICLK) \
	COMP_NOGATE(TS_CLK_TX536_SPI_3_SSICLK) \
	COMP_NOGATE(TS_CLK_TX536_SPI_4_SSICLK) \
	COMP_NOMUX(TS_CLK_TX536_TOP_TMR_T5CLK) \
	COMP_NOMUX(TS_CLK_TX536_TOP_TMR_T6CLK) \
	COMP_NOMUX(TS_CLK_TX536_TOP_TMR_T7CLK) \
	COMP_NOMUX(TS_CLK_TX536_TOP_TMR_T8CLK) \
	COMP_NOMUX(TS_CLK_TX536_SEC_TMR_T2CLK) \
	COMP_NOMUX(TS_CLK_TX536_SEC_TMR_T3CLK) \
	COMP_NODIV(TS_CLK_TX536_CHIP_OCLK_0) \
	COMP_NODIV(TS_CLK_TX536_CHIP_OCLK_1) \
	COMP_NODIV(TS_CLK_TX536_CHIP_OCLK_2) \
	COMP_NODIV(TS_CLK_TX536_CHIP_OCLK_3) \
	COMP_NOMUX(TS_CLK_TX536_VO_BUS_CLK) \
	COMP_NOMUX(TS_CLK_TX536_DP650_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_DMA2MIPI_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_NEMADC_HCLK) \
	COMP_NOMUX(TS_CLK_TX536_HDMI_TX_HCLK) \
	COMP_NOMUX(TS_CLK_TX536_NEMADC_CCLK) \
	COMP_NOMUX(TS_CLK_TX536_DMA2MIPI_CCLK) \
	COMP_NOMUX(TS_CLK_TX536_DP650_MCLK) \
	COMP_NOMUX(TS_CLK_TX536_DP650_PXL_CLK) \
	COMP_NODIV(TS_CLK_TX536_MIPI_TXPHY_REF_CLK) \
	COMP_NODIV(TS_CLK_TX536_MIPI_TXPHY_CFG_CLK) \
	COMP_NOMUX(TS_CLK_TX536_MCTL_P0_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_MCTL_P1_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_MCTL_P2_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_MCTL_P3_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_MCTL_P4_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_MCTL_P5_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_VI_BUS_PCLK) \
	COMP(TS_CLK_TX536_ISP_SCLK) \
	COMP_NOMUX(TS_CLK_TX536_VPE_CCLK) \
	COMP_NODIV(TS_CLK_TX536_MIPI_RXPHY0_CFGCLK) \
	COMP_NODIV(TS_CLK_TX536_MIPI_RXPHY1_CFGCLK) \
	COMP_NODIV(TS_CLK_TX536_MIPI_RXPHY2_CFGCLK) \
	COMP_NOMUX(TS_CLK_TX536_ISP_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_VPE_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_WAVE_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_CODA_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_VPU_CFG_PCLK) \
	COMP_NOMUX(TS_CLK_TX536_WAVE_CCLK) \
	COMP_NOMUX(TS_CLK_TX536_WAVE_BCLK) \
	COMP_NOMUX(TS_CLK_TX536_CODA_CCLK) \
	COMP_NOMUX(TS_CLK_TX536_RNE_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_RCE_ACLK) \
	COMP(TS_CLK_TX536_AI_MEM_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_RCE_CCLK) \
	COMP_NOMUX(TS_CLK_TX536_RNE_CCLK) \
	COMP_NOGATE(TS_CLK_TX536_MCU_NOC_CLK) \
	COMP(TS_CLK_TX536_MCU_DDR_ACLK) \
	COMP_NOMUX(TS_CLK_TX536_DVP_ACLK) \
	COMP_NODIV(TS_CLK_TX536_AUDIO_PCLK) \
	COMP_NOMUX(TS_CLK_TX536_DVP_MCLK) \
	COMP_NODIV(TS_CLK_TX536_AUDIO_MCLK) \
	COMP_NOGATE(TS_CLK_TX536_UART_0_SCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_0_ICCLK) \
	COMP_NOGATE(TS_CLK_TX536_I2C_1_ICCLK) \
	COMP_NOMUX(TS_CLK_TX536_TMR_T2CLK) \
	COMP_NOMUX(TS_CLK_TX536_TMR_T3CLK) \
	COMP_NOMUX(TS_CLK_TX536_TMR_T4CLK) \
	COMP_NODIV(TS_CLK_TX536_CHIP_OCLK_4) \
	COMP_DIV_ONLY(TS_CLK_TX536_A53_ACLKM) \
	COMP_DIV_ONLY(TS_CLK_TX536_A53_DBG_PCLK) \
	COMP_DIV_ONLY(TS_CLK_TX536_A53_ATCLK) \
	COMP_DIV_ONLY(TS_CLK_TX536_A53_CNT_CLK) \
	COMP_DIV_ONLY(TS_CLK_TX536_DMAC_1_ACP_ACLK) \
	COMP_DIV_ONLY(TS_CLK_TX536_TOP_BUS_HCLK) \
	COMP_DIV_ONLY(TS_CLK_TX536_TOP_BUS_PCLK) \
	COMP_DIV_ONLY(TS_CLK_TX536_GDC_MCLK) \
	COMP_DIV_ONLY(TS_CLK_TX536_BT1120TX_HCLK) \
	COMP_DIV_ONLY(TS_CLK_TX536_AISYS_HCLK) \
	COMP_DIV_ONLY(TS_CLK_TX536_MCU_BUS_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_CX400_TSCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_DMAC_0_ACLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_DMAC_1_ACLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_BOOTROM_HCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_GMAC_BUS_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MMU_ACLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_GIC400_ACLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_BT1120_TX_BUS_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_BT1120_RX_BUS_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_OSPI_BUS_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_NFC_HCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_GDC_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_CVE_HCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_GPU_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_TOP_WDT_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_SEC_WDT_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_TOP_TMR_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_SEC_TMR_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_TOP_GPIO_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_OTPC_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_ADC_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_TOP_PADC_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MAILBOX_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_SPI_0_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_SPI_1_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_SPI_2_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_SPI_3_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_SPI_4_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2S_0_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2S_1_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_UART_1_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_UART_2_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_UART_3_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_UART_4_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_UART_5_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_UART_6_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_USI_2_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_USI_3_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_2_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_3_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_4_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_5_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_6_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_7_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_8_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_9_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_TOP_TMR_T4CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MII_RXCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_PTP_REF_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_GMII_TX_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_DP650_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_DMA2MIPI_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_CSI_DEV_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_DSI_HOST_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_HDMI_TX_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_DSI_HOST_IPI_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_HDMI_TX_PXL_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_HDMI_TX_CFG_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MCTL_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MCTL_DDRC_CLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_CSI_HOST_0_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_CSI_HOST_1_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_CSI_HOST_2_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_VPE_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_HDR_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_CSI_HOST_0_PXLCLK0) \
	COMP_GATE_ONLY(TS_CLK_TX536_CSI_HOST_0_PXLCLK1) \
	COMP_GATE_ONLY(TS_CLK_TX536_CSI_HOST_0_PXLCLK2) \
	COMP_GATE_ONLY(TS_CLK_TX536_CSI_HOST_1_PXLCLK0) \
	COMP_GATE_ONLY(TS_CLK_TX536_CSI_HOST_2_PXLCLK0) \
	COMP_GATE_ONLY(TS_CLK_TX536_TNR_CCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_TNR_HCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_HDR_ACLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_TNR_ACLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_WAVE_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_CODA_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_RNE_HCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_RCE_HCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_AI_ISP_HCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_PWM_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MCU_PADC_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MCU_TMR_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MCU_WDT_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_UART_0_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_0_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_I2C_1_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_USI_0_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_USI_1_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MCU_GPIO_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MCU_RAM_ACLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_DVP_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_SYS_REG_PCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MCU_RNE_ACLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_DMAC2_HCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_AUDIO_HCLK) \
	COMP_GATE_ONLY(TS_CLK_TX536_MCU_CLK24M)

#define _COMPIFY(id) TS_CLK_TX536_COMP_##id
#define COMPIFY(id) _COMPIFY(id)

enum ts_comp_ids {
#define COMP_FULL(id, ...) COMPIFY(id),
	COMP_LIST
#undef COMP_FULL
};

static const struct ts_comp_params ts_tx536_comps[] = {
#define COMP_FULL(id, _mux, _div, _gate) \
	[COMPIFY(id)] = { \
		.mux = (_mux), \
		.div = (_div), \
		.gate = (_gate), \
	},
	COMP_LIST
#undef COMP_FULL
};

#undef COMP
#undef COMP_ID
#undef COMP_NOMUX
#undef COMP_NOMUX_ID
#undef COMP_LIST

static int clk_tx536_is_frac_divider(const char *name)
{
	u32 i;
	char *frac_div_arr[] = {"uart_1_sclk", "uart_2_sclk", "uart_3_sclk",
		"uart_4_sclk", "uart_5_sclk", "uart_6_sclk", "uart_0_sclk"};

	for (i = 0; i < ARRAY_SIZE(frac_div_arr); i++) {
		if (!strncmp(frac_div_arr[i], name, strlen(frac_div_arr[i])))
			return true;
	}
	return false;
}

/* Create all sub-clocks, and then register the composite clock */
struct clk *clk_tx536_register_comp(const struct ts_comp_params *params,
					void *base, const char *name,
					const char *parent)
{
	const char *const *parent_names;
	int num_parents;
	struct clk *comp;
	const struct clk_ops *mux_ops;
	const struct clk_ops *div_ops;
	const struct clk_ops *gate_ops;
	struct clk_mux *mux;
	struct clk_gate *gate;
	void *div;
	struct clk *clk;
	u32 div_id = 0;

	if (params->mux == TS_CLK_MUX_NONE) {
		if (!parent) {
			printf("MUX_NONE with parent not NULL\n");
			return ERR_PTR(-EINVAL);
		}

		mux_ops = NULL;
		mux = NULL;
		parent_names = &parent;
		num_parents = 1;
	} else {
		mux_ops = &clk_mux_ops;
		mux = ts_create_mux(&ts_tx536_muxes[params->mux], base);
		if (!mux) {
			printf("create clk %s mux %d failed\n", name, params->mux);
			return ERR_PTR(-ENOMEM);
		}

		parent_names = mux->parent_names;
		num_parents = mux->num_parents;
	}

	if (params->div == TS_CLK_DIV_NONE) {
		div_ops = NULL;
		div = NULL;
	} else {
		div_id = params->div;
		if (clk_tx536_is_frac_divider(name)) {
			div_ops = &clk_fractional_divider_ops;
			div = (struct clk_fractional_divider *)ts_create_fractional_div(&ts_tx536_divs[div_id], base);
			clk = &((struct clk_fractional_divider *)div)->clk;
		} else {
			div_ops = &clk_divider_ops;
			div = (struct clk_divider *)ts_create_div(&ts_tx536_divs[div_id], base, NULL);
			clk = &((struct clk_divider *)div)->clk;
		}

		if (!div) {
			printf("create clk %s div %d failed\n", name, div_id);
			comp = ERR_PTR(-ENOMEM);
			goto cleanup_mux;
		}
	}

	if (params->gate == TS_CLK_GATE_NONE) {
		gate_ops = NULL;
		gate = NULL;
	} else {
		gate_ops = &clk_gate_ops;
		gate = ts_create_gate(&ts_tx536_gates[params->gate], base);
		if (!gate) {
			printf("create clk %s gate %d failed\n", name, params->gate);
			comp = ERR_PTR(-ENOMEM);
			goto cleanup_div;
		}
	}

	comp = clk_register_composite(NULL, name, parent_names, num_parents,
					(mux ? &mux->clk : NULL), mux_ops,
					(div ? clk : NULL), div_ops,
					(gate ? &gate->clk : NULL), gate_ops, 0);
	if (IS_ERR(comp)) {
		printf("register composite %s failed\n", name);
		goto cleanup_gate;
	}
	return comp;

cleanup_gate:
	if (gate)
		free(gate);
cleanup_div:
	if (div)
		free(div);
cleanup_mux:
	if (mux)
		free(mux);
	return comp;
}

static int clk_tx536_register_plls(struct ts_clk_params *paras)
{
	void *top_base = paras->top_base;
	void *mcu_base = paras->mcu_base;
	void __iomem *reg;
	void __iomem *lock;
	int i;

	for (i = 0; i < ARRAY_SIZE(ts_tx536_plls); i++) {
		struct ts_pll_params *params = &ts_tx536_plls[i];
		if (params->id == TS_CLK_TX536_MCU_PLL) {
			reg = mcu_base + params->off;
			lock = mcu_base + MCU_PLL_STATUS;
		} else {
			reg = top_base + params->off;
			lock = top_base + params->lock_off;
		}

		clk_dm(params->id,
			ts_register_pll(params->name, &osc_in[0], reg, lock,
				params->shift, params->width, PLL_REG_MODE_LOOSELY));
	}

	/* fix-frequency clocks for plls */
	clk_dm(TS_CLK_TX536_CPU_PLL_D2,
		ts_clk_fixed_divider("cpu_pll_d2", "cpu_pll", 2));
	clk_dm(TS_CLK_TX536_CPU_PLL_D4,
		ts_clk_fixed_divider("cpu_pll_d4", "cpu_pll", 4));
	clk_dm(TS_CLK_TX536_CPU_PLL_D6,
		ts_clk_fixed_divider("cpu_pll_d6", "cpu_pll", 6));
	clk_dm(TS_CLK_TX536_CPU_PLL_D8,
		ts_clk_fixed_divider("cpu_pll_d8", "cpu_pll", 8));
	clk_dm(TS_CLK_TX536_CPU_PLL_D16,
		ts_clk_fixed_divider("cpu_pll_d16", "cpu_pll", 16));
	clk_dm(TS_CLK_TX536_CPU_PLL_D24,
		ts_clk_fixed_divider("cpu_pll_d24", "cpu_pll", 24));
	clk_dm(TS_CLK_TX536_CPU_PLL_D32,
		ts_clk_fixed_divider("cpu_pll_d32", "cpu_pll", 32));
	clk_dm(TS_CLK_TX536_CPU_PLL_D64,
		ts_clk_fixed_divider("cpu_pll_d64", "cpu_pll", 64));
	clk_dm(TS_CLK_TX536_BUS_PLL_D2,
		ts_clk_fixed_divider("bus_pll_d2", "bus_pll", 2));
	clk_dm(TS_CLK_TX536_BUS_PLL_D3,
		ts_clk_fixed_divider("bus_pll_d3", "bus_pll", 3));
	clk_dm(TS_CLK_TX536_BUS_PLL_D4,
		ts_clk_fixed_divider("bus_pll_d4", "bus_pll", 4));
	clk_dm(TS_CLK_TX536_BUS_PLL_D6,
		ts_clk_fixed_divider("bus_pll_d6", "bus_pll", 6));
	clk_dm(TS_CLK_TX536_BUS_PLL_D8,
		ts_clk_fixed_divider("bus_pll_d8", "bus_pll", 8));
	clk_dm(TS_CLK_TX536_BUS_PLL_D12,
		ts_clk_fixed_divider("bus_pll_d12", "bus_pll", 12));
	clk_dm(TS_CLK_TX536_BUS_PLL_D16,
		ts_clk_fixed_divider("bus_pll_d16", "bus_pll", 16));
	clk_dm(TS_CLK_TX536_DISP_PLL_D2,
		ts_clk_fixed_divider("disp_pll_d2", "disp_pll", 2));
	clk_dm(TS_CLK_TX536_DISP_PLL_D4,
		ts_clk_fixed_divider("disp_pll_d4", "disp_pll", 4));
	clk_dm(TS_CLK_TX536_DISP_PLL_D8,
		ts_clk_fixed_divider("disp_pll_d8", "disp_pll", 8));
	clk_dm(TS_CLK_TX536_DISP_PLL_D16,
		ts_clk_fixed_divider("disp_pll_d16", "disp_pll", 16));
	clk_dm(TS_CLK_TX536_DISP_PLL_D32,
		ts_clk_fixed_divider("disp_pll_d32", "disp_pll", 32));

	clk_dm(TS_CLK_TX536_MCU_PLL_D2,
		ts_clk_fixed_divider("mcu_pll_d2", "mcu_pll", 2));
	clk_dm(TS_CLK_TX536_MCU_PLL_D3,
		ts_clk_fixed_divider("mcu_pll_d3", "mcu_pll", 3));
	clk_dm(TS_CLK_TX536_MCU_PLL_D4,
		ts_clk_fixed_divider("mcu_pll_d4", "mcu_pll", 4));
	clk_dm(TS_CLK_TX536_MCU_PLL_D6,
		ts_clk_fixed_divider("mcu_pll_d6", "mcu_pll", 6));
	clk_dm(TS_CLK_TX536_MCU_PLL_D8,
		ts_clk_fixed_divider("mcu_pll_d8", "mcu_pll", 8));
	clk_dm(TS_CLK_TX536_MCU_PLL_D18,
		ts_clk_fixed_divider("mcu_pll_d18", "mcu_pll", 18));
	clk_dm(TS_CLK_TX536_MCU_PLL_D24,
		ts_clk_fixed_divider("mcu_pll_d24", "mcu_pll", 24));
	clk_dm(TS_CLK_TX536_MCU_PLL_D36,
		ts_clk_fixed_divider("mcu_pll_d36", "mcu_pll", 36));
	clk_dm(TS_CLK_TX536_MCU_PLL_D48,
		ts_clk_fixed_divider("mcu_pll_d48", "mcu_pll", 48));
	clk_dm(TS_CLK_TX536_MCU_PLL_D54,
		ts_clk_fixed_divider("mcu_pll_d54", "mcu_pll", 54));
	clk_dm(TS_CLK_TX536_MCU_PLL_D108,
		ts_clk_fixed_divider("mcu_pll_d108", "mcu_pll", 108));
	return 0;
}

static int clk_tx536_register_comps(struct ts_clk_params *paras)
{
	void *top_base = paras->top_base;
	void *mcu_base = paras->mcu_base;

#define REGISTER_COMP(id, name) \
		clk_dm(id, \
			   clk_tx536_register_comp(&ts_tx536_comps[COMPIFY(id)], \
						(id < TS_CLK_TX536_MCU_CLK_START) ? top_base : mcu_base, \
						name, NULL))

	//printf("--TS_CLK_MUX_NONE  %d--\n", TS_CLK_MUX_NONE);
	//printf("--TS_CLK_DIV_NONE  %d--\n", TS_CLK_DIV_NONE);
	//printf("--TS_CLK_GATE_NONE %d--\n", TS_CLK_GATE_NONE);

	REGISTER_COMP(TS_CLK_TX536_A53_CLKIN, "a53_clkin");
	REGISTER_COMP(TS_CLK_TX536_CX400_ATCLK, "cx400_atclk");
	REGISTER_COMP(TS_CLK_TX536_CX400_DAP_CLK, "cx400_dap_clk");
	REGISTER_COMP(TS_CLK_TX536_CX400_DP_CLK, "cx400_dp_clk");
	REGISTER_COMP(TS_CLK_TX536_TOP_NOC_CLK, "top_noc_clk");
	REGISTER_COMP(TS_CLK_TX536_MSHC_0_HCLK, "mshc_0_hclk");
	REGISTER_COMP(TS_CLK_TX536_MSHC_1_HCLK, "mshc_1_hclk");
	REGISTER_COMP(TS_CLK_TX536_CRYPTO_BUS_CLK, "crypto_bus_clk");
	REGISTER_COMP(TS_CLK_TX536_USB3C_BUS_CLK, "usb3c_bus_clk");
	REGISTER_COMP(TS_CLK_TX536_GDC_ACLK, "gdc_aclk");
	REGISTER_COMP(TS_CLK_TX536_CVE_ACLK, "cve_aclk");
	REGISTER_COMP(TS_CLK_TX536_GPU_ACLK, "gpu_aclk");
	REGISTER_COMP(TS_CLK_TX536_GMAC_ACLK, "gmac_aclk");
	REGISTER_COMP(TS_CLK_TX536_MSHC_0_BCLK, "mshc_0_bclk");
	REGISTER_COMP(TS_CLK_TX536_MSHC_1_BCLK, "mshc_1_bclk");
	REGISTER_COMP(TS_CLK_TX536_USB_PHY_REFCLK, "usb_phy_refclk");
	REGISTER_COMP(TS_CLK_TX536_USB_CTL_REFCLK, "usb_ctl_refclk");
	REGISTER_COMP(TS_CLK_TX536_NFC_CLKB, "nfc_clkb");
	REGISTER_COMP(TS_CLK_TX536_BT1120TX_ACLK, "bt1120tx_aclk");
	REGISTER_COMP(TS_CLK_TX536_BT1120RX_ACLK, "bt1120rx_aclk");
	REGISTER_COMP(TS_CLK_TX536_OSPI_HCLK, "ospi_hclk");
	REGISTER_COMP(TS_CLK_TX536_OSPI_REF_CLK, "ospi_ref_clk");
	REGISTER_COMP(TS_CLK_TX536_I2C_2_ICCLK, "i2c_2_icclk");
	REGISTER_COMP(TS_CLK_TX536_I2C_3_ICCLK, "i2c_3_icclk");
	REGISTER_COMP(TS_CLK_TX536_I2C_4_ICCLK, "i2c_4_icclk");
	REGISTER_COMP(TS_CLK_TX536_I2C_5_ICCLK, "i2c_5_icclk");
	REGISTER_COMP(TS_CLK_TX536_I2C_6_ICCLK, "i2c_6_icclk");
	REGISTER_COMP(TS_CLK_TX536_I2C_7_ICCLK, "i2c_7_icclk");
	REGISTER_COMP(TS_CLK_TX536_I2C_8_ICCLK, "i2c_8_icclk");
	REGISTER_COMP(TS_CLK_TX536_I2C_9_ICCLK, "i2c_9_icclk");
	REGISTER_COMP(TS_CLK_TX536_UART_1_SCLK, "uart_1_sclk");
	REGISTER_COMP(TS_CLK_TX536_UART_2_SCLK, "uart_2_sclk");
	REGISTER_COMP(TS_CLK_TX536_UART_3_SCLK, "uart_3_sclk");
	REGISTER_COMP(TS_CLK_TX536_UART_4_SCLK, "uart_4_sclk");
	REGISTER_COMP(TS_CLK_TX536_UART_5_SCLK, "uart_5_sclk");
	REGISTER_COMP(TS_CLK_TX536_UART_6_SCLK, "uart_6_sclk");
	REGISTER_COMP(TS_CLK_TX536_SPI_0_SSICLK, "spi_0_ssiclk");
	REGISTER_COMP(TS_CLK_TX536_SPI_1_SSICLK, "spi_1_ssiclk");
	REGISTER_COMP(TS_CLK_TX536_SPI_2_SSICLK, "spi_2_ssiclk");
	REGISTER_COMP(TS_CLK_TX536_SPI_3_SSICLK, "spi_3_ssiclk");
	REGISTER_COMP(TS_CLK_TX536_SPI_4_SSICLK, "spi_4_ssiclk");
	REGISTER_COMP(TS_CLK_TX536_CHIP_OCLK_0, "chip_oclk_0");
	REGISTER_COMP(TS_CLK_TX536_CHIP_OCLK_1, "chip_oclk_1");
	REGISTER_COMP(TS_CLK_TX536_CHIP_OCLK_2, "chip_oclk_2");
	REGISTER_COMP(TS_CLK_TX536_CHIP_OCLK_3, "chip_oclk_3");
	REGISTER_COMP(TS_CLK_TX536_MIPI_TXPHY_REF_CLK, "mipi_txphy_ref_clk");
	REGISTER_COMP(TS_CLK_TX536_MIPI_TXPHY_CFG_CLK, "mipi_txphy_cfg_clk");
	REGISTER_COMP(TS_CLK_TX536_ISP_SCLK, "isp_sclk");
	REGISTER_COMP(TS_CLK_TX536_MIPI_RXPHY0_CFGCLK, "mipi_rxphy0_cfgclk");
	REGISTER_COMP(TS_CLK_TX536_MIPI_RXPHY1_CFGCLK, "mipi_rxphy1_cfgclk");
	REGISTER_COMP(TS_CLK_TX536_MIPI_RXPHY2_CFGCLK, "mipi_rxphy2_cfgclk");
	REGISTER_COMP(TS_CLK_TX536_AI_MEM_ACLK, "ai_mem_aclk");
	REGISTER_COMP(TS_CLK_TX536_MCU_NOC_CLK, "mcu_noc_clk");
	REGISTER_COMP(TS_CLK_TX536_MCU_DDR_ACLK, "mcu_ddr_aclk");
	REGISTER_COMP(TS_CLK_TX536_AUDIO_PCLK, "aud_pclk");
	REGISTER_COMP(TS_CLK_TX536_AUDIO_MCLK, "aud_mclk");
	REGISTER_COMP(TS_CLK_TX536_UART_0_SCLK, "uart_0_sclk");
	REGISTER_COMP(TS_CLK_TX536_I2C_0_ICCLK, "i2c_0_icclk");
	REGISTER_COMP(TS_CLK_TX536_I2C_1_ICCLK, "i2c_1_icclk");
	REGISTER_COMP(TS_CLK_TX536_CHIP_OCLK_4, "chip_oclk_4");

#undef REGISTER_COMP

	/* divider "mcu_bus_pclk" is parent of comp "dvp_aclk"), register here */
	clk_dm(TS_CLK_TX536_MCU_BUS_PCLK,
		clk_tx536_register_comp(&ts_tx536_comps[COMPIFY(TS_CLK_TX536_MCU_BUS_PCLK)],
				mcu_base, "mcu_bus_pclk", "mcu_noc_clk"));
	return 0;
}

static int clk_tx536_register_comps_without_mux(struct ts_clk_params *paras)
{
	void *top_base = paras->top_base;
	void *mcu_base = paras->mcu_base;

		/* Dividing clocks, no mux */
#define REGISTER_COMP_NOMUX(id, name, parent) \
		clk_dm(id, \
			   clk_tx536_register_comp(&ts_tx536_comps[COMPIFY(id)], \
						(id < TS_CLK_TX536_MCU_CLK_START) ? top_base : mcu_base, \
						name, parent))

	REGISTER_COMP_NOMUX(TS_CLK_TX536_CVE_CCLK, "cve_cclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_GPU_CCLK, "gpu_cclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_I2S0_OCLK, "i2s0_oclk", "aud_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_I2S1_OCLK, "i2s1_oclk", "aud_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_I2S0_MCLK, "i2s0_mclk", "i2s0_oclk");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_I2S1_MCLK, "i2s1_mclk", "i2s1_oclk");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_TOP_TMR_T5CLK, "top_tmr_t5clk", &osc_in[0]);
	REGISTER_COMP_NOMUX(TS_CLK_TX536_TOP_TMR_T6CLK, "top_tmr_t6clk", "cpu_pll_d4");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_TOP_TMR_T7CLK, "top_tmr_t7clk", "cpu_pll_d4");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_TOP_TMR_T8CLK, "top_tmr_t8clk", "cpu_pll_d4");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_SEC_TMR_T2CLK, "sec_tmr_t2clk", &osc_in[0]);
	REGISTER_COMP_NOMUX(TS_CLK_TX536_SEC_TMR_T3CLK, "sec_tmr_t3clk", "cpu_pll_d4");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_VO_BUS_CLK, "vo_bus_clk", "bus_pll_d6");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_DP650_ACLK, "dp650_aclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_DMA2MIPI_ACLK, "dma2mipi_aclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_NEMADC_HCLK, "nemadc_hclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_HDMI_TX_HCLK, "hdmi_tx_hclk", "bus_pll_d8");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_NEMADC_CCLK, "nemadc_cclk", "disp_pll_d4");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_DMA2MIPI_CCLK, "dma2mipi_cclk", "disp_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_DP650_MCLK, "dp650_mclk", "disp_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_DP650_PXL_CLK, "dp650_pxl_clk", "disp_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_MCTL_P0_ACLK, "mctl_p0_aclk", "cpu_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_MCTL_P1_ACLK, "mctl_p1_aclk", "bus_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_MCTL_P2_ACLK, "mctl_p2_aclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_MCTL_P3_ACLK, "mctl_p3_aclk", "mcu_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_MCTL_P4_ACLK, "mctl_p4_aclk", "disp_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_MCTL_P5_ACLK, "mctl_p5_aclk", "bus_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_VI_BUS_PCLK, "vi_bus_pclk", "bus_pll_d4");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_VPE_CCLK, "vpe_cclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_ISP_ACLK, "isp_aclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_VPE_ACLK, "vpe_aclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_WAVE_ACLK, "wave_aclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_CODA_ACLK, "coda_aclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_VPU_CFG_PCLK, "vpu_cfg_pclk", "bus_pll_d6");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_WAVE_CCLK, "wave_cclk", "bus_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_WAVE_BCLK, "wave_bclk", "cpu_pll_d4");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_CODA_CCLK, "coda_cclk", "bus_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_RNE_ACLK, "rne_aclk", "cpu_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_RCE_ACLK, "rce_aclk", "cpu_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_RCE_CCLK, "rce_cclk", "bus_pll_d2");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_RNE_CCLK, "rne_cclk", "ai_pll");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_DVP_ACLK, "dvp_aclk", "mcu_bus_pclk");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_DVP_MCLK, "dvp_mclk", "mcu_pll_d4");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_TMR_T2CLK, "tmr_t2clk", &osc_in[0]);
	REGISTER_COMP_NOMUX(TS_CLK_TX536_TMR_T3CLK, "tmr_t3clk", "mcu_pll_d4");
	REGISTER_COMP_NOMUX(TS_CLK_TX536_TMR_T4CLK, "tmr_t4clk", "mcu_pll_d4");

#undef REGISTER_COMP_NOMUX
	return 0;
}

static int clk_tx536_register_dividers(struct ts_clk_params *paras)
{
	void *top_base = paras->top_base;
	void *mcu_base = paras->mcu_base;

	/* Dividing clocks, comp with divider only */
#define REGISTER_DIV(id, name, parent) \
	clk_dm(id, \
		   clk_tx536_register_comp(&ts_tx536_comps[COMPIFY(id)], \
					(id < TS_CLK_TX536_MCU_CLK_START) ? top_base : mcu_base, \
					name, parent))

	REGISTER_DIV(TS_CLK_TX536_A53_ACLKM, "a53_aclkm", "a53_clkin");
	REGISTER_DIV(TS_CLK_TX536_A53_DBG_PCLK, "a53_dbg_pclk", "a53_clkin");
	REGISTER_DIV(TS_CLK_TX536_A53_ATCLK, "a53_atclk", "a53_clkin");
	REGISTER_DIV(TS_CLK_TX536_A53_CNT_CLK, "a53_cnt_clk", "a53_clkin");
	REGISTER_DIV(TS_CLK_TX536_DMAC_1_ACP_ACLK, "dmac_1_acp_aclk", "a53_clkin");
	REGISTER_DIV(TS_CLK_TX536_TOP_BUS_HCLK, "top_bus_hclk", "top_noc_clk");
	REGISTER_DIV(TS_CLK_TX536_TOP_BUS_PCLK, "top_bus_pclk", "top_bus_hclk");
	REGISTER_DIV(TS_CLK_TX536_GDC_MCLK, "gdc_mclk", "bus_pll_d2");
	REGISTER_DIV(TS_CLK_TX536_BT1120TX_HCLK, "bt1120tx_hclk", "disp_pll_d4");
	REGISTER_DIV(TS_CLK_TX536_AISYS_HCLK, "aisys_hclk", "bus_pll_d4");
	//REGISTER_DIV(TS_CLK_TX536_MCU_BUS_PCLK, "mcu_bus_pclk", "mcu_noc_clk");

#undef REGISTER_DIV
	return 0;
}

static int clk_tx536_register_gates(struct ts_clk_params *paras)
{
	void *top_base = paras->top_base;
	void *mcu_base = paras->mcu_base;

		/* Dividing clocks, comp with gate only */
#define REGISTER_GATE(id, name, parent) \
	clk_dm(id, \
		   clk_tx536_register_comp(&ts_tx536_comps[COMPIFY(id)], \
					(id < TS_CLK_TX536_MCU_CLK_START) ? top_base : mcu_base, \
					name, parent))

	REGISTER_GATE(TS_CLK_TX536_CX400_TSCLK, "cx400_tsclk", "a53_clkin");
	REGISTER_GATE(TS_CLK_TX536_DMAC_0_ACLK, "dmac_0_aclk", "top_noc_clk");
	REGISTER_GATE(TS_CLK_TX536_DMAC_1_ACLK, "dmac_1_aclk", "top_bus_hclk");
	REGISTER_GATE(TS_CLK_TX536_BOOTROM_HCLK, "bootrom_hclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_GMAC_BUS_CLK, "gmac_bus_clk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_MMU_ACLK, "mmu_aclk", "top_noc_clk");
	REGISTER_GATE(TS_CLK_TX536_GIC400_ACLK, "gic400_aclk", "top_bus_hclk");
	REGISTER_GATE(TS_CLK_TX536_BT1120_TX_BUS_CLK, "bt1120_tx_bus_clk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_BT1120_RX_BUS_CLK, "bt1120_rx_bus_clk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_OSPI_BUS_CLK, "ospi_bus_clk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_NFC_HCLK, "nfc_hclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_GDC_PCLK, "gdc_pclk", "bus_pll_d2");
	REGISTER_GATE(TS_CLK_TX536_CVE_HCLK, "cve_hclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_GPU_PCLK, "gpu_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_TOP_WDT_PCLK, "top_wdt_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_SEC_WDT_PCLK, "sec_wdt_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_TOP_TMR_PCLK, "top_tmr_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_SEC_TMR_PCLK, "sec_tmr_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_TOP_GPIO_PCLK, "top_gpio_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_OTPC_PCLK, "otpc_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_ADC_PCLK, "adc_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_TOP_PADC_PCLK, "top_padc_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_MAILBOX_PCLK, "mailbox_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_SPI_0_PCLK, "spi_0_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_SPI_1_PCLK, "spi_1_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_SPI_2_PCLK, "spi_2_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_SPI_3_PCLK, "spi_3_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_SPI_4_PCLK, "spi_4_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2S_0_PCLK, "i2s_0_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2S_1_PCLK, "i2s_1_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_UART_1_PCLK, "uart_1_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_UART_2_PCLK, "uart_2_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_UART_3_PCLK, "uart_3_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_UART_4_PCLK, "uart_4_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_UART_5_PCLK, "uart_5_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_UART_6_PCLK, "uart_6_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_USI_2_PCLK, "usi_2_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_USI_3_PCLK, "usi_3_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_2_PCLK, "i2c_2_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_3_PCLK, "i2c_3_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_4_PCLK, "i2c_4_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_5_PCLK, "i2c_5_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_6_PCLK, "i2c_6_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_7_PCLK, "i2c_7_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_8_PCLK, "i2c_8_pclk", "top_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_9_PCLK, "i2c_9_pclk", "top_bus_pclk");
	//REGISTER_GATE(TS_CLK_TX536_TOP_TMR_T3CLK, "top_tmr_t3clk", "unknown");
	REGISTER_GATE(TS_CLK_TX536_TOP_TMR_T4CLK, "top_tmr_t4clk", "cpu_pll_d8");
	REGISTER_GATE(TS_CLK_TX536_MII_RXCLK, "mii_rxclk", &osc_in[0]);
	//REGISTER_GATE(TS_CLK_TX536_MII_TXCLK, "mii_rxclk", "unknown");
	//REGISTER_GATE(TS_CLK_TX536_MAC_CLK_RMII, "mac_clk_rmii", "unknown"); // ephy
	//REGISTER_GATE(TS_CLK_TX536_RMII_TX_CLK, "rmii_tx_clk", "unknown"); // ephy
	REGISTER_GATE(TS_CLK_TX536_GMII_TX_CLK, "gmii_tx_clk", &osc_in[0]); // ephy
	REGISTER_GATE(TS_CLK_TX536_PTP_REF_CLK, "gmii_ptp_clk", &osc_in[0]); // ephy
	REGISTER_GATE(TS_CLK_TX536_DP650_PCLK, "cp650_pclk", "vo_bus_clk");
	REGISTER_GATE(TS_CLK_TX536_DMA2MIPI_PCLK, "dma2mipi_pclk", "vo_bus_clk");
	REGISTER_GATE(TS_CLK_TX536_CSI_DEV_PCLK, "csi_dev_pclk", "vo_bus_clk");
	REGISTER_GATE(TS_CLK_TX536_DSI_HOST_PCLK, "dsi_host_pclk", "vo_bus_clk");
	REGISTER_GATE(TS_CLK_TX536_HDMI_TX_PCLK, "hdmi_tx_pclk", "vo_bus_clk");
	REGISTER_GATE(TS_CLK_TX536_DSI_HOST_IPI_CLK, "dsi_host_ipi_clk", "disp_pll");
	REGISTER_GATE(TS_CLK_TX536_HDMI_TX_PXL_CLK, "hdmi_tx_pxl_clk", "dp650_pxl_clk");
	REGISTER_GATE(TS_CLK_TX536_HDMI_TX_CFG_CLK, "hdmi_tx_cfg_clk", &osc_in[0]);
	REGISTER_GATE(TS_CLK_TX536_MCTL_PCLK, "mctl_pclk", "bus_pll_d12");
	REGISTER_GATE(TS_CLK_TX536_MCTL_DDRC_CLK, "mctl_ddrc_clk", "ddr_pll");
	REGISTER_GATE(TS_CLK_TX536_CSI_HOST_0_PCLK, "csi_host_0_pclk", "vi_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_CSI_HOST_1_PCLK, "csi_host_1_pclk", "vi_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_CSI_HOST_2_PCLK, "csi_host_2_pclk", "vi_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_VPE_PCLK, "vpe_pclk", "vi_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_HDR_PCLK, "hdr_pclk", "vi_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_CSI_HOST_0_PXLCLK0, "csi_host_0_pxlclk0", "isp_sclk");
	REGISTER_GATE(TS_CLK_TX536_CSI_HOST_0_PXLCLK1, "csi_host_0_pxlclk1", "isp_sclk");
	REGISTER_GATE(TS_CLK_TX536_CSI_HOST_0_PXLCLK2, "csi_host_0_pxlclk2", "isp_sclk");
	REGISTER_GATE(TS_CLK_TX536_CSI_HOST_1_PXLCLK0, "csi_host_1_pxlclk0", "isp_sclk");
	REGISTER_GATE(TS_CLK_TX536_CSI_HOST_2_PXLCLK0, "csi_host_2_pxlclk0", "isp_sclk");
	REGISTER_GATE(TS_CLK_TX536_TNR_CCLK, "tnr_cclk", "isp_sclk");
	REGISTER_GATE(TS_CLK_TX536_TNR_HCLK, "tnr_hclk", "isp_sclk");
	REGISTER_GATE(TS_CLK_TX536_HDR_ACLK, "hdr_aclk", "isp_aclk");
	REGISTER_GATE(TS_CLK_TX536_TNR_ACLK, "tnr_aclk", "isp_aclk");
	REGISTER_GATE(TS_CLK_TX536_WAVE_PCLK, "wave_pclk", "vpu_cfg_pclk");
	REGISTER_GATE(TS_CLK_TX536_CODA_PCLK, "coda_pclk", "vpu_cfg_pclk");
	REGISTER_GATE(TS_CLK_TX536_RNE_HCLK, "rne_hclk", "aisys_hclk");
	REGISTER_GATE(TS_CLK_TX536_RCE_HCLK, "rce_hclk", "aisys_hclk");
	REGISTER_GATE(TS_CLK_TX536_AI_ISP_HCLK, "ai_isp_hclk", "aisys_hclk");
	REGISTER_GATE(TS_CLK_TX536_PWM_PCLK, "pwm_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_MCU_PADC_PCLK, "mcu_padc_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_MCU_TMR_PCLK, "mcu_tmr_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_MCU_WDT_PCLK, "mcu_wdt_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_UART_0_PCLK, "uart_0_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_0_PCLK, "i2c_0_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_I2C_1_PCLK, "i2c_1_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_USI_0_PCLK, "usi_0_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_USI_1_PCLK, "usi_1_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_MCU_GPIO_PCLK, "mcu_gpio_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_MCU_RAM_ACLK, "mcu_ram_pclk", "mcu_noc_clk");
	REGISTER_GATE(TS_CLK_TX536_DVP_PCLK, "dvp_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_SYS_REG_PCLK, "sysreg_pclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_MCU_RNE_ACLK, "mcu_rne_aclk", "mcu_noc_clk");
	REGISTER_GATE(TS_CLK_TX536_DMAC2_HCLK, "dmac2_hclk", "mcu_noc_clk");
	REGISTER_GATE(TS_CLK_TX536_AUDIO_HCLK, "audio_hclk", "mcu_bus_pclk");
	REGISTER_GATE(TS_CLK_TX536_MCU_CLK24M, "mcu_clk24m", "mcu_pll_d8");

#undef REGISTER_GATE
	return 0;
}

int ts_clk_init_funcs(struct ts_clk_reg_funcs *pfuncs)
{
	if (!pfuncs)
		return -EINVAL;

	pfuncs->register_plls = clk_tx536_register_plls;
	pfuncs->register_comps = clk_tx536_register_comps;
	pfuncs->register_comps_without_mux = clk_tx536_register_comps_without_mux;
	pfuncs->register_dividers = clk_tx536_register_dividers;
	pfuncs->register_gates = clk_tx536_register_gates;
	return 0;
}

