# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021 Tsingmicro Co., Ltd
#

obj-$(CONFIG_ARCH_TS_TX536) += ts_clk.o ts_pll.o clk_tx536.o
obj-$(CONFIG_ARCH_TS_TX5215) += ts_clk.o ts_pll.o clk_tx5215.o 
obj-$(CONFIG_ARCH_TS_TX5112) += ts_clk.o ts_pll.o clk_tx5112.o
obj-$(CONFIG_ARCH_TS_TX5336) += ts_clk.o ts_tx5336_pll.o clk_tx5336.o 

