# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021 Tsingmicro Co., Ltd
#

obj-$(CONFIG_ARCH_TS) += ts_clk.o 
obj-$(CONFIG_ARCH_TS_TX536) += clk_tx536.o ts_pll.o
obj-$(CONFIG_ARCH_TS_TX5215) += clk_tx5215.o ts_pll.o
obj-$(CONFIG_ARCH_TS_TX5112) += clk_tx5112.o ts_pll.o
obj-$(CONFIG_ARCH_TS_TX5336) += clk_tx5336.o ts_pll_tx5336.o
