# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2004-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_CMD_DMA) += dma/sys_smmu.o
obj-$(CONFIG_CMD_DMA) += dma/sys_exception.o
obj-$(CONFIG_CMD_DMA) += dma/qw_dma_pl330.o
obj-$(CONFIG_CMD_DMA) += dma/sample_dma330.o
