obj-$(CONFIG_PINCTRL_TS_TX536)		+= pinctrl-ts-tx536.o
obj-$(CONFIG_PINCTRL_TS_TX5215)		+= pinctrl-ts-tx5215.o
obj-$(CONFIG_PINCTRL_TS_TX5112)		+= pinctrl-ts-tx5112.o
obj-$(CONFIG_PINCTRL_TS_TX5336)		+= pinctrl-ts-tx5336.o