#
# Tsingmicro Soc drivers
#
obj-$(CONFIG_ARCH_TS_TX536) += io_lock.o
obj-$(CONFIG_ARCH_TS_TX5336) += io_lock.o
obj-$(CONFIG_TS_DMA_HEAP) += dma-heap/
obj-$(CONFIG_TS_DMA_TRACE) += ts_dma_trace.o
obj-$(CONFIG_TS_MUX_TX536) += smu-tx536.o noc.o cgu.o grf.o sgrf.o
obj-$(CONFIG_TS_MUX_TX5215) += smu-tx5215.o sys.o
obj-$(CONFIG_TS_MUX_TX5112) += smu-tx5112.o sys.o
obj-$(CONFIG_TS_MUX_TX5336) += smu-tx5336.o sys.o
obj-y += cache_op.o
obj-y += wrap/