// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2022-2022 Tsingmicro, Inc.
 */

#define LOG_CATEGORY UCLASS_RESET

#include <common.h>
#include <dm.h>
#include <dm/device_compat.h>
#include <reset-uclass.h>
#include <linux/io.h>
#include <dt-bindings/reset/ts-tx536-resets.h>

/* TOP_RGU*/
#define A53_RST_CTL0			0x000
#define A53_RST_CTL1			0x004
#define A53_SYS_RST_CTL			0x008
#define CX400_RST_CTL			0x010
#define GIC400_RST_CTL			0x018
#define BOOTROM_RST_CTL			0x01C
#define DMAC0_RST_CTL			0x020
#define DMAC1_RST_CTL			0x024
#define MMU_RST_CTL				0x02C
#define MSHC0_RST_CTL			0x030
#define MSHC1_RST_CTL			0x034
#define GDC_RST_CTL				0x038
#define GMAC_RST_CTL			0x040
#define USB3C_RST_CTL			0x048
#define I2C_RST_CTL0			0x050
#define I2C_RST_CTL1			0x054
#define I2C_RST_CTL2			0x058
#define I2C_RST_CTL3			0x05C
#define UART_RST_CTL0			0x060
#define UART_RST_CTL1			0x064
#define UART_RST_CTL2			0x068
#define SPI_RST_CTL0			0x070
#define SPI_RST_CTL1			0x074
#define SPI_RST_CTL2			0x078
#define TOP_TMR_RST_CTL			0x080
#define SEC_TMR_RST_CTL			0x084
#define TOP_WDT_RST_CTL			0x090
#define SEC_WDT_RST_CTL			0x094
#define USI_RST_CTL				0x0A0
#define I2S_RST_CTL				0x0A8
#define TOP_PADC_RST_CTL		0x0B0
#define MAILBOX_RST_CTL			0x0B4
#define TOP_ADC_RST_CTL			0x0B8
#define TOP_OTPC_RST_CTL		0x0BC
#define BT1120_RST_CTL			0x0C0
#define OSPI_CTL_RST_CTL		0x0C4
#define NAND_CTL_RST_CTL		0x0C8
#define CRYPTO_RST_CTL			0x0D0
#define CVE_RST_CTL				0x0D4
#define GPU_RST_CTL				0x0D8
#define DMA2MIPI_RST_CTL		0x100
#define DP650_RST_CTL			0x104
#define NEMADC_RST_CTL			0x108
#define VO_MIPI_RST_CTL			0x10C
#define HDMI_TX_RST_CTL			0x110
#define VO_SYS_RST_CTL			0x118
#define MCTL_RST_CTL0			0x130
#define MCTL_RST_CTL1			0x134
#define MCTL_RST_CTL2			0x138
#define DDR_SYS_RST_CTL			0x13C
#define ISP_RST_CTL				0x150
#define HDR_RST_CTL				0x154
#define VI_MIPI_RST_CTL			0x158
#define VPE_RST_CTL				0x15C
#define TNR_RST_CTL				0x160
#define VI_SYS_RST_CTL			0x164
#define WAVE_RST_CTL			0x170
#define CODA_RST_CTL			0x174
#define VPU_SYS_RST_CTL			0x178
#define RNE_RST_CTL				0x190
#define RCE_RST_CTL				0x194
#define AIISP_RST_CTL			0x198
#define AIMEM_RST_CTL			0x19C
#define AI_SYS_RST_CTL			0x1A0

/* MCU_CRGU */
#define CK804_RST_CTL			0x104
#define MCU_RNE_RST_CTL			0x108
#define DVP_RST_CTL				0x110
#define MCU_RAM_RST_CTL			0x118
#define DMAC2_RST_CTL			0x11C
#define UART0_RST_CTL			0x120
#define AUD_RST_CTL				0x128
#define MCU_USI_RST_CTL			0x130
#define I2C0_RST_CTL			0x140
#define I2C1_RST_CTL			0x144
#define MCU_PADC_RST_CTL		0x150
#define MCU_TMR_RST_CTL			0x158
#define MCU_WDT_RST_CTL			0x15C
#define MCU_PWM_RST_CTL			0x160
#define SYS_REG_RST_CTL			0x164

#define TOP_RGU			0
#define MCU_RGU			1

#define RESET_LIST \
	RESET(TS_RST_A53_CORE0, TOP_RGU, A53_RST_CTL0, 0) \
	RESET(TS_RST_A53_CORE1, TOP_RGU, A53_RST_CTL0, 1) \
	RESET(TS_RST_A53_L2CACHE, TOP_RGU, A53_RST_CTL0, 2) \
	RESET(TS_RST_A53_DBG, TOP_RGU, A53_RST_CTL0, 3) \
	RESET(TS_RST_SYS_GLOBAL, TOP_RGU, A53_SYS_RST_CTL, 0) \
	RESET(TS_RST_CX400, TOP_RGU, CX400_RST_CTL, 0) \
	RESET(TS_RST_GIC400, TOP_RGU, GIC400_RST_CTL, 0) \
	RESET(TS_RST_BOOTROM, TOP_RGU, BOOTROM_RST_CTL, 0) \
	RESET(TS_RST_DMAC0, TOP_RGU, DMAC0_RST_CTL, 0) \
	RESET(TS_RST_DMAC1_AXI, TOP_RGU, DMAC1_RST_CTL, 0) \
	RESET(TS_RST_DMAC1_ACP, TOP_RGU, DMAC1_RST_CTL, 1) \
	RESET(TS_RST_MMU, TOP_RGU, MMU_RST_CTL, 0) \
	RESET(TS_RST_MSHC0_SLAVE, TOP_RGU, MSHC0_RST_CTL, 0) \
	RESET(TS_RST_MSHC0_MASTER, TOP_RGU, MSHC0_RST_CTL, 1) \
	RESET(TS_RST_MSHC0_BASE_CLK, TOP_RGU, MSHC0_RST_CTL, 3) \
	RESET(TS_RST_MSHC0_GLOBAL, TOP_RGU, MSHC0_RST_CTL, 4) \
	RESET(TS_RST_MSHC0_LOWFREQ_CLK, TOP_RGU, MSHC0_RST_CTL, 5) \
	RESET(TS_RST_MSHC0_TIMER, TOP_RGU, MSHC0_RST_CTL, 6) \
	RESET(TS_RST_MSHC1_SLAVE, TOP_RGU, MSHC1_RST_CTL, 0) \
	RESET(TS_RST_MSHC1_MASTER, TOP_RGU, MSHC1_RST_CTL, 1) \
	RESET(TS_RST_MSHC1_BASE_CLK, TOP_RGU, MSHC1_RST_CTL, 3) \
	RESET(TS_RST_MSHC1_GLOBAL, TOP_RGU, MSHC1_RST_CTL, 4) \
	RESET(TS_RST_MSHC1_LOWFREQ_CLK, TOP_RGU, MSHC1_RST_CTL, 5) \
	RESET(TS_RST_MSHC1_TIMER, TOP_RGU, MSHC1_RST_CTL, 6) \
	RESET(TS_RST_GDC_AXI, TOP_RGU, GDC_RST_CTL, 1) \
	RESET(TS_RST_GDC_MAIN_FUN_CLK, TOP_RGU, GDC_RST_CTL, 2) \
	RESET(TS_RST_GDC_GLOBAL, TOP_RGU, GDC_RST_CTL, 3) \
	RESET(TS_RST_GMAC_AXI, TOP_RGU, GMAC_RST_CTL, 0) \
	RESET(TS_RST_GMAC_AHB, TOP_RGU, GMAC_RST_CTL, 1) \
	RESET(TS_RST_GMAC_GLOBAL, TOP_RGU, GMAC_RST_CTL, 4) \
	RESET(TS_RST_USB3C, TOP_RGU, USB3C_RST_CTL, 0) \
	RESET(TS_RST_I2C2_APB, TOP_RGU, I2C_RST_CTL0, 0) \
	RESET(TS_RST_I2C2_SERIAL_INTF, TOP_RGU, I2C_RST_CTL0, 1) \
	RESET(TS_RST_I2C2_GLOBAL, TOP_RGU, I2C_RST_CTL0, 2) \
	RESET(TS_RST_I2C3_APB, TOP_RGU, I2C_RST_CTL0, 16) \
	RESET(TS_RST_I2C3_SERIAL_INTF, TOP_RGU, I2C_RST_CTL0, 17) \
	RESET(TS_RST_I2C3_GLOBAL, TOP_RGU, I2C_RST_CTL0, 18) \
	RESET(TS_RST_I2C4_APB, TOP_RGU, I2C_RST_CTL1, 0) \
	RESET(TS_RST_I2C4_SERIAL_INTF, TOP_RGU, I2C_RST_CTL1, 1) \
	RESET(TS_RST_I2C4_GLOBAL, TOP_RGU, I2C_RST_CTL1, 2) \
	RESET(TS_RST_I2C5_APB, TOP_RGU, I2C_RST_CTL1, 16) \
	RESET(TS_RST_I2C5_SERIAL_INTF, TOP_RGU, I2C_RST_CTL1, 17) \
	RESET(TS_RST_I2C5_GLOBAL, TOP_RGU, I2C_RST_CTL1, 18) \
	RESET(TS_RST_I2C6_APB, TOP_RGU, I2C_RST_CTL2, 0) \
	RESET(TS_RST_I2C6_SERIAL_INTF, TOP_RGU, I2C_RST_CTL2, 1) \
	RESET(TS_RST_I2C6_GLOBAL, TOP_RGU, I2C_RST_CTL2, 2) \
	RESET(TS_RST_I2C7_APB, TOP_RGU, I2C_RST_CTL2, 16) \
	RESET(TS_RST_I2C7_SERIAL_INTF, TOP_RGU, I2C_RST_CTL2, 17) \
	RESET(TS_RST_I2C7_GLOBAL, TOP_RGU, I2C_RST_CTL2, 18) \
	RESET(TS_RST_I2C8_APB, TOP_RGU, I2C_RST_CTL3, 0) \
	RESET(TS_RST_I2C8_SERIAL_INTF, TOP_RGU, I2C_RST_CTL3, 1) \
	RESET(TS_RST_I2C8_GLOBAL, TOP_RGU, I2C_RST_CTL3, 2) \
	RESET(TS_RST_I2C9_APB, TOP_RGU, I2C_RST_CTL3, 16) \
	RESET(TS_RST_I2C9_SERIAL_INTF, TOP_RGU, I2C_RST_CTL3, 17) \
	RESET(TS_RST_I2C9_GLOBAL, TOP_RGU, I2C_RST_CTL3, 18) \
	RESET(TS_RST_UART1_APB, TOP_RGU, UART_RST_CTL0, 0) \
	RESET(TS_RST_UART1_SERIAL_INTF, TOP_RGU, UART_RST_CTL0, 1) \
	RESET(TS_RST_UART1_GLOBAL, TOP_RGU, UART_RST_CTL0, 2) \
	RESET(TS_RST_UART2_APB, TOP_RGU, UART_RST_CTL0, 16) \
	RESET(TS_RST_UART2_SERIAL_INTF, TOP_RGU, UART_RST_CTL0, 17) \
	RESET(TS_RST_UART2_GLOBAL, TOP_RGU, UART_RST_CTL0, 18) \
	RESET(TS_RST_UART3_APB, TOP_RGU, UART_RST_CTL1, 0) \
	RESET(TS_RST_UART3_SERIAL_INTF, TOP_RGU, UART_RST_CTL1, 1) \
	RESET(TS_RST_UART3_GLOBAL, TOP_RGU, UART_RST_CTL1, 2) \
	RESET(TS_RST_UART4_APB, TOP_RGU, UART_RST_CTL1, 16) \
	RESET(TS_RST_UART4_SERIAL_INTF, TOP_RGU, UART_RST_CTL1, 17) \
	RESET(TS_RST_UART4_GLOBAL, TOP_RGU, UART_RST_CTL1, 18) \
	RESET(TS_RST_UART5_APB, TOP_RGU, UART_RST_CTL2, 0) \
	RESET(TS_RST_UART5_SERIAL_INTF, TOP_RGU, UART_RST_CTL2, 1) \
	RESET(TS_RST_UART5_GLOBAL, TOP_RGU, UART_RST_CTL2, 2) \
	RESET(TS_RST_UART6_APB, TOP_RGU, UART_RST_CTL2, 16) \
	RESET(TS_RST_UART6_SERIAL_INTF, TOP_RGU, UART_RST_CTL2, 17) \
	RESET(TS_RST_UART6_GLOBAL, TOP_RGU, UART_RST_CTL2, 18) \
	RESET(TS_RST_SPI0_APB, TOP_RGU, SPI_RST_CTL0, 0) \
	RESET(TS_RST_SPI0_SERIAL_INTF, TOP_RGU, SPI_RST_CTL0, 1) \
	RESET(TS_RST_SPI0_GLOBAL, TOP_RGU, SPI_RST_CTL0, 2) \
	RESET(TS_RST_SPI1_APB, TOP_RGU, SPI_RST_CTL0, 16) \
	RESET(TS_RST_SPI1_SERIAL_INTF, TOP_RGU, SPI_RST_CTL0, 17) \
	RESET(TS_RST_SPI1_GLOBAL, TOP_RGU, SPI_RST_CTL0, 18) \
	RESET(TS_RST_SPI2_APB, TOP_RGU, SPI_RST_CTL1, 0) \
	RESET(TS_RST_SPI2_SERIAL_INTF, TOP_RGU, SPI_RST_CTL1, 1) \
	RESET(TS_RST_SPI2_GLOBAL, TOP_RGU, SPI_RST_CTL1, 2) \
	RESET(TS_RST_SPI3_APB, TOP_RGU, SPI_RST_CTL1, 16) \
	RESET(TS_RST_SPI3_SERIAL_INTF, TOP_RGU, SPI_RST_CTL1, 17) \
	RESET(TS_RST_SPI3_GLOBAL, TOP_RGU, SPI_RST_CTL1, 18) \
	RESET(TS_RST_SPI4_APB, TOP_RGU, SPI_RST_CTL2, 0) \
	RESET(TS_RST_SPI4_SERIAL_INTF, TOP_RGU, SPI_RST_CTL2, 1) \
	RESET(TS_RST_SPI4_GLOBAL, TOP_RGU, SPI_RST_CTL2, 2) \
	RESET(TS_RST_TOP_TIMER_APB, TOP_RGU, TOP_TMR_RST_CTL, 0) \
	RESET(TS_RST_TOP_TIMER1, TOP_RGU, TOP_TMR_RST_CTL, 1) \
	RESET(TS_RST_TOP_TIMER2, TOP_RGU, TOP_TMR_RST_CTL, 2) \
	RESET(TS_RST_TOP_TIMER3, TOP_RGU, TOP_TMR_RST_CTL, 3) \
	RESET(TS_RST_TOP_TIMER4, TOP_RGU, TOP_TMR_RST_CTL, 4) \
	RESET(TS_RST_TOP_TIMER5, TOP_RGU, TOP_TMR_RST_CTL, 5) \
	RESET(TS_RST_TOP_TIMER6, TOP_RGU, TOP_TMR_RST_CTL, 6) \
	RESET(TS_RST_TOP_TIMER7, TOP_RGU, TOP_TMR_RST_CTL, 7) \
	RESET(TS_RST_TOP_TIMER8, TOP_RGU, TOP_TMR_RST_CTL, 8) \
	RESET(TS_RST_TOP_TIMER_GLOBAL, TOP_RGU, TOP_TMR_RST_CTL, 9) \
	RESET(TS_RST_SEC_TIMER_APB, TOP_RGU, SEC_TMR_RST_CTL, 0) \
	RESET(TS_RST_SEC_TIMER1, TOP_RGU, SEC_TMR_RST_CTL, 1) \
	RESET(TS_RST_SEC_TIMER2, TOP_RGU, SEC_TMR_RST_CTL, 2) \
	RESET(TS_RST_SEC_TIMER3, TOP_RGU, SEC_TMR_RST_CTL, 3) \
	RESET(TS_RST_SEC_TIMER_GLOBAL, TOP_RGU, SEC_TMR_RST_CTL, 4) \
	RESET(TS_RST_TOP_WDT_APB, TOP_RGU, TOP_WDT_RST_CTL, 0) \
	RESET(TS_RST_TOP_WDT_TICK_TIMER, TOP_RGU, TOP_WDT_RST_CTL, 1) \
	RESET(TS_RST_TOP_WDT_GLOBAL, TOP_RGU, TOP_WDT_RST_CTL, 2) \
	RESET(TS_RST_SEC_WDT_APB, TOP_RGU, SEC_WDT_RST_CTL, 0) \
	RESET(TS_RST_SEC_WDT_TICK_TIMER, TOP_RGU, SEC_WDT_RST_CTL, 1) \
	RESET(TS_RST_SEC_WDT_GLOBAL, TOP_RGU, SEC_WDT_RST_CTL, 2) \
	RESET(TS_RST_USI2, TOP_RGU, USI_RST_CTL, 0) \
	RESET(TS_RST_USI3, TOP_RGU, USI_RST_CTL, 16) \
	RESET(TS_RST_I2S0_APB, TOP_RGU, I2S_RST_CTL, 0) \
	RESET(TS_RST_I2S0_SERIAL_INTF, TOP_RGU, I2S_RST_CTL, 1) \
	RESET(TS_RST_I2S0_GLOBAL, TOP_RGU, I2S_RST_CTL, 2) \
	RESET(TS_RST_I2S1_APB, TOP_RGU, I2S_RST_CTL, 16) \
	RESET(TS_RST_I2S1_SERIAL_INTF, TOP_RGU, I2S_RST_CTL, 17) \
	RESET(TS_RST_I2S1_GLOBAL, TOP_RGU, I2S_RST_CTL, 18) \
	RESET(TS_RST_TOP_PADC, TOP_RGU, TOP_PADC_RST_CTL, 0) \
	RESET(TS_RST_TOP_GPIO, TOP_RGU, TOP_PADC_RST_CTL, 16) \
	RESET(TS_RST_MAILBOX, TOP_RGU, MAILBOX_RST_CTL, 0) \
	RESET(TS_RST_TOP_ADC, TOP_RGU, TOP_ADC_RST_CTL, 0) \
	RESET(TS_RST_TOP_OTPC, TOP_RGU, TOP_OTPC_RST_CTL, 0) \
	RESET(TS_RST_BT1120_RX_APB, TOP_RGU, BT1120_RST_CTL, 0) \
	RESET(TS_RST_BT1120_RX_AXI, TOP_RGU, BT1120_RST_CTL, 1) \
	RESET(TS_RST_BT1120_RX_GLOBAL, TOP_RGU, BT1120_RST_CTL, 2) \
	RESET(TS_RST_BT1120_TX_GLOBAL, TOP_RGU, BT1120_RST_CTL, 18) \
	RESET(TS_RST_OSPI_APB, TOP_RGU, OSPI_CTL_RST_CTL, 0) \
	RESET(TS_RST_OSPI_AHB, TOP_RGU, OSPI_CTL_RST_CTL, 1) \
	RESET(TS_RST_OSPI_SPI_INTF, TOP_RGU, OSPI_CTL_RST_CTL, 2) \
	RESET(TS_RST_OSPI_GLOBAL, TOP_RGU, OSPI_CTL_RST_CTL, 3) \
	RESET(TS_RST_NFC_AHB, TOP_RGU, NAND_CTL_RST_CTL, 0) \
	RESET(TS_RST_NFC_FUNC_BLOCK, TOP_RGU, NAND_CTL_RST_CTL, 1) \
	RESET(TS_RST_NFC_GLOBAL, TOP_RGU, NAND_CTL_RST_CTL, 2) \
	RESET(TS_RST_CRYPTO, TOP_RGU, CRYPTO_RST_CTL, 0) \
	RESET(TS_RST_CVE_AHB, TOP_RGU, CVE_RST_CTL, 0) \
	RESET(TS_RST_CVE_AXI, TOP_RGU, CVE_RST_CTL, 1) \
	RESET(TS_RST_CVE_CORE, TOP_RGU, CVE_RST_CTL, 2) \
	RESET(TS_RST_CVE_GLOBAL, TOP_RGU, CVE_RST_CTL, 3) \
	RESET(TS_RST_GPU, TOP_RGU, GPU_RST_CTL, 0) \
	RESET(TS_RST_DMA2MIPI_APB, TOP_RGU, DMA2MIPI_RST_CTL, 0) \
	RESET(TS_RST_DMA2MIPI_AXI, TOP_RGU, DMA2MIPI_RST_CTL, 1) \
	RESET(TS_RST_DMA2MIPI_CORE, TOP_RGU, DMA2MIPI_RST_CTL, 2) \
	RESET(TS_RST_DMA2MIPI_GLOBAL, TOP_RGU, DMA2MIPI_RST_CTL, 3) \
	RESET(TS_RST_DP650, TOP_RGU, DP650_RST_CTL, 0) \
	RESET(TS_RST_NEMADC, TOP_RGU, NEMADC_RST_CTL, 0) \
	RESET(TS_RST_CSI_DEV_APB, TOP_RGU, VO_MIPI_RST_CTL, 0) \
	RESET(TS_RST_DSI_HOST_APB, TOP_RGU, VO_MIPI_RST_CTL, 16) \
	RESET(TS_RST_HDMI_TX_APB, TOP_RGU, HDMI_TX_RST_CTL, 0) \
	RESET(TS_RST_HDMI_TX_MAIN, TOP_RGU, HDMI_TX_RST_CTL, 1) \
	RESET(TS_RST_HDMI_TX_AHB, TOP_RGU, HDMI_TX_RST_CTL, 2) \
	RESET(TS_RST_HDMI_TX_GLOBAL, TOP_RGU, HDMI_TX_RST_CTL, 3) \
	RESET(TS_RST_VO_SYS_GLOBAL, TOP_RGU, VO_SYS_RST_CTL, 0) \
	RESET(TS_RST_MCTL_P0, TOP_RGU, MCTL_RST_CTL0, 0) \
	RESET(TS_RST_MCTL_P1, TOP_RGU, MCTL_RST_CTL0, 1) \
	RESET(TS_RST_MCTL_P2, TOP_RGU, MCTL_RST_CTL0, 2) \
	RESET(TS_RST_MCTL_P3, TOP_RGU, MCTL_RST_CTL0, 3) \
	RESET(TS_RST_MCTL_P4, TOP_RGU, MCTL_RST_CTL0, 4) \
	RESET(TS_RST_MCTL_P5, TOP_RGU, MCTL_RST_CTL0, 5) \
	RESET(TS_RST_MCTL_AXI_GLOBAL, TOP_RGU, MCTL_RST_CTL0, 16) \
	RESET(TS_RST_MCTL_APB, TOP_RGU, MCTL_RST_CTL1, 0) \
	RESET(TS_RST_MCTL_PHY_PUB, TOP_RGU, MCTL_RST_CTL1, 1) \
	RESET(TS_RST_MCTL_APB_GLOBAL, TOP_RGU, MCTL_RST_CTL1, 16) \
	RESET(TS_RST_MCTL_DDRC, TOP_RGU, MCTL_RST_CTL2, 0) \
	RESET(TS_RST_MCTL_DDR_PHY_PUB, TOP_RGU, MCTL_RST_CTL2, 1) \
	RESET(TS_RST_DDR_SYS_GLOBAL, TOP_RGU, DDR_SYS_RST_CTL, 0) \
	RESET(TS_RST_ISP_AHB, TOP_RGU, ISP_RST_CTL, 0) \
	RESET(TS_RST_ISP_AXI, TOP_RGU, ISP_RST_CTL, 1) \
	RESET(TS_RST_ISP_CORE, TOP_RGU, ISP_RST_CTL, 2) \
	RESET(TS_RST_ISP_GLOBAL, TOP_RGU, ISP_RST_CTL, 3) \
	RESET(TS_RST_HDR_AHB, TOP_RGU, HDR_RST_CTL, 0) \
	RESET(TS_RST_HDR_AXI, TOP_RGU, HDR_RST_CTL, 1) \
	RESET(TS_RST_HDR_GLOBAL, TOP_RGU, HDR_RST_CTL, 3) \
	RESET(TS_RST_CSI_HOST0_AHB, TOP_RGU, VI_MIPI_RST_CTL, 0) \
	RESET(TS_RST_CSI_HOST1_AHB, TOP_RGU, VI_MIPI_RST_CTL, 1) \
	RESET(TS_RST_CSI_HOST2_AHB, TOP_RGU, VI_MIPI_RST_CTL, 2) \
	RESET(TS_RST_VPE_APB, TOP_RGU, VPE_RST_CTL, 0) \
	RESET(TS_RST_VPE_AXI, TOP_RGU, VPE_RST_CTL, 1) \
	RESET(TS_RST_VPE_CORE, TOP_RGU, VPE_RST_CTL, 2) \
	RESET(TS_RST_VPE_GLOBAL, TOP_RGU, VPE_RST_CTL, 3) \
	RESET(TS_RST_TNR_AHB, TOP_RGU, TNR_RST_CTL, 0) \
	RESET(TS_RST_TNR_AXI, TOP_RGU, TNR_RST_CTL, 1) \
	RESET(TS_RST_TNR_CORE, TOP_RGU, TNR_RST_CTL, 2) \
	RESET(TS_RST_TNR_GLOBAL, TOP_RGU, TNR_RST_CTL, 3) \
	RESET(TS_RST_VI_SYS_GLOBAL, TOP_RGU, VI_SYS_RST_CTL, 0) \
	RESET(TS_RST_WAVE_APB, TOP_RGU, WAVE_RST_CTL, 0) \
	RESET(TS_RST_WAVE_AXI, TOP_RGU, WAVE_RST_CTL, 1) \
	RESET(TS_RST_WAVE_CORE, TOP_RGU, WAVE_RST_CTL, 2) \
	RESET(TS_RST_WAVE_BPU, TOP_RGU, WAVE_RST_CTL, 3) \
	RESET(TS_RST_WAVE_GLOBAL, TOP_RGU, WAVE_RST_CTL, 4) \
	RESET(TS_RST_CODA_APB, TOP_RGU, CODA_RST_CTL, 0) \
	RESET(TS_RST_CODA_AXI, TOP_RGU, CODA_RST_CTL, 1) \
	RESET(TS_RST_CODA_CORE, TOP_RGU, CODA_RST_CTL, 2) \
	RESET(TS_RST_CODA_GLOBAL, TOP_RGU, CODA_RST_CTL, 3) \
	RESET(TS_RST_VPU_SYS_GLOBAL, TOP_RGU, VPU_SYS_RST_CTL, 0) \
	RESET(TS_RST_RNE_AHB, TOP_RGU, RNE_RST_CTL, 0) \
	RESET(TS_RST_RNE_AXI, TOP_RGU, RNE_RST_CTL, 1) \
	RESET(TS_RST_RNE_CORE, TOP_RGU, RNE_RST_CTL, 2) \
	RESET(TS_RST_RNE_MEM, TOP_RGU, RNE_RST_CTL, 3) \
	RESET(TS_RST_RNE_GLOBAL, TOP_RGU, RNE_RST_CTL, 4) \
	RESET(TS_RST_RCE_AHB, TOP_RGU, RCE_RST_CTL, 0) \
	RESET(TS_RST_RCE_AXI, TOP_RGU, RCE_RST_CTL, 1) \
	RESET(TS_RST_RCE_CORE, TOP_RGU, RCE_RST_CTL, 2) \
	RESET(TS_RST_RCE_MEM, TOP_RGU, RCE_RST_CTL, 3) \
	RESET(TS_RST_RCE_GLOBAL, TOP_RGU, RCE_RST_CTL, 4) \
	RESET(TS_RST_AIISP_AHB, TOP_RGU, AIISP_RST_CTL, 0) \
	RESET(TS_RST_AIISP_CORE, TOP_RGU, AIISP_RST_CTL, 1) \
	RESET(TS_RST_AIISP_GLOBAL, TOP_RGU, AIISP_RST_CTL, 2) \
	RESET(TS_RST_AIMEM_AXI, TOP_RGU, AIMEM_RST_CTL, 0) \
	RESET(TS_RST_AIMEM_GLOBAL, TOP_RGU, AIMEM_RST_CTL, 2) \
	RESET(TS_RST_AISYS_GLOBAL, TOP_RGU, AI_SYS_RST_CTL, 0) \
	RESET(TS_RST_CK804, MCU_RGU, CK804_RST_CTL, 0) \
	RESET(TS_RST_MCU_RNE, MCU_RGU, MCU_RNE_RST_CTL, 0) \
	RESET(TS_RST_DVP_AXI, MCU_RGU, DVP_RST_CTL, 0) \
	RESET(TS_RST_DVP_APB, MCU_RGU, DVP_RST_CTL, 1) \
	RESET(TS_RST_DVP_MAIN_FUNC, MCU_RGU, DVP_RST_CTL, 2) \
	RESET(TS_RST_DVP_GLOBAL, MCU_RGU, DVP_RST_CTL, 3) \
	RESET(TS_RST_MCU_RAM, MCU_RGU, MCU_RAM_RST_CTL, 0) \
	RESET(TS_RST_DMAC2, MCU_RGU, DMAC2_RST_CTL, 0) \
	RESET(TS_RST_UART0_APB, MCU_RGU, UART0_RST_CTL, 0) \
	RESET(TS_RST_UART0_SERIAL_INTF, MCU_RGU, UART0_RST_CTL, 1) \
	RESET(TS_RST_UART0_GLOBAL, MCU_RGU, UART0_RST_CTL, 4) \
	RESET(TS_RST_AUD_APB, MCU_RGU, AUD_RST_CTL, 0) \
	RESET(TS_RST_AUD_AHB, MCU_RGU, AUD_RST_CTL, 1) \
	RESET(TS_RST_AUD_CODEC, MCU_RGU, AUD_RST_CTL, 2) \
	RESET(TS_RST_AUD_GLOBAL, MCU_RGU, AUD_RST_CTL, 4) \
	RESET(TS_RST_USI0_APB, MCU_RGU, MCU_USI_RST_CTL, 0) \
	RESET(TS_RST_USI1_APB, MCU_RGU, MCU_USI_RST_CTL, 8) \
	RESET(TS_RST_I2C0_APB, MCU_RGU, I2C0_RST_CTL, 0) \
	RESET(TS_RST_I2C0_SERIAL_INTF, MCU_RGU, I2C0_RST_CTL, 1) \
	RESET(TS_RST_I2C0_GLOBAL, MCU_RGU, I2C0_RST_CTL, 2) \
	RESET(TS_RST_I2C1_APB, MCU_RGU, I2C1_RST_CTL, 0) \
	RESET(TS_RST_I2C1_SERIAL_INTF, MCU_RGU, I2C1_RST_CTL, 1) \
	RESET(TS_RST_I2C1_GLOBAL, MCU_RGU, I2C1_RST_CTL, 2) \
	RESET(TS_RST_MCU_PADC, MCU_RGU, MCU_PADC_RST_CTL, 0) \
	RESET(TS_RST_MCU_GPIO, MCU_RGU, MCU_PADC_RST_CTL, 8) \
	RESET(TS_RST_MCU_TIMER_APB, MCU_RGU, MCU_TMR_RST_CTL, 0) \
	RESET(TS_RST_MCU_TIMER1, MCU_RGU, MCU_TMR_RST_CTL, 4) \
	RESET(TS_RST_MCU_TIMER2, MCU_RGU, MCU_TMR_RST_CTL, 5) \
	RESET(TS_RST_MCU_TIMER3, MCU_RGU, MCU_TMR_RST_CTL, 6) \
	RESET(TS_RST_MCU_TIMER4, MCU_RGU, MCU_TMR_RST_CTL, 7) \
	RESET(TS_RST_MCU_TIMER_GLOBAL, MCU_RGU, MCU_TMR_RST_CTL, 8) \
	RESET(TS_RST_MCU_WDT_APB, MCU_RGU, MCU_WDT_RST_CTL, 0) \
	RESET(TS_RST_MCU_WDT_TIMER, MCU_RGU, MCU_WDT_RST_CTL, 1) \
	RESET(TS_RST_MCU_WDT_GLOBAL, MCU_RGU, MCU_WDT_RST_CTL, 4) \
	RESET(TS_RST_MCU_PWM_APB, MCU_RGU, MCU_PWM_RST_CTL, 0) \
	RESET(TS_RST_MCU_SYS_REG_APB, MCU_RGU, SYS_REG_RST_CTL, 0)

#define _RESETIFY(id) TS_RST_##id
#define RESETIFY(id) _RESETIFY(id)

enum ts_rst_ids {
#define RESET(id, ...) RESETIFY(id),
	RESET_LIST
#undef RESET
	TS_RST_NONE,
};

struct ts_rst_params {
	u32 id;
	u32 rgu;
	u32 off;
	u8 bit_idx;
};

static const struct ts_rst_params ts_resets[] = {
#define RESET(_id, _rgu, _off, _idx) \
	[RESETIFY(_id)] = { \
		.id = (_id), \
		.rgu = (_rgu), \
		.off = (_off), \
		.bit_idx = (_idx), \
	},
	RESET_LIST
#undef RESET
};

#undef RESET_LIST

#define SET_BIT(data, bit)		((data) | (0x1 << (bit)))
#define CLEAR_BIT(data, bit)		((data) & (~(0x1 << (bit))))

enum ts_pm_reset_action {
	PM_RESET_ACTION_RELEASE = 0,
	PM_RESET_ACTION_ASSERT  = 1,
	PM_RESET_ACTION_PULSE   = 2,
};

struct tx536_reset_priv {
	u32 nr_reset;
	void __iomem *top_rgu_base;
	void __iomem *mcu_rgu_base;
};

const struct ts_rst_params *ts_reset_search_by_id(u32 reset)
{
	const struct ts_rst_params *para = NULL;
	u32 i;

	for (i = 0; i < ARRAY_SIZE(ts_resets); i++) {
		if (ts_resets[i].id == reset) {
			para = &ts_resets[i];
			break;
		}
	}
	return para;
}

static int tx536_pm_reset_assert(struct reset_ctl *rst,
				const enum ts_pm_reset_action assert_flag)
{
	struct tx536_reset_priv *priv = dev_get_priv(rst->dev);
	const struct ts_rst_params *para = NULL;
	const u32 reset = rst->id;
	void __iomem *addr;
	u32 val;
	
	debug("--%s id %d, flag %d--\n", __func__, reset, assert_flag);
	para = ts_reset_search_by_id(reset);
	if (!para)
		return -ENOENT;

	addr = (para->rgu == TOP_RGU) ? priv->top_rgu_base : priv->mcu_rgu_base;
	addr += para->off;
	val = readl(addr);
	debug("--reg %p, bit %d--\n", addr, para->bit_idx);
	debug("--ori val 0x%x--\n", val);
	if (assert_flag == PM_RESET_ACTION_ASSERT)
		val = SET_BIT(val, para->bit_idx);
	else if (assert_flag == PM_RESET_ACTION_RELEASE)
		val = CLEAR_BIT(val, para->bit_idx);
	debug("--new val 0x%x--\n", val);
	writel(val, addr);
	return 0;
}

static int tx536_reset_assert(struct reset_ctl *rst)
{
	dev_dbg(rst->dev, "%s(rst=%p) (id=%lu)\n", __func__, rst, rst->id);
	return tx536_pm_reset_assert(rst, PM_RESET_ACTION_ASSERT);
}

static int tx536_reset_deassert(struct reset_ctl *rst)
{
	debug("%s(rst=%p) (id=%lu)\n", __func__, rst, rst->id);
	return tx536_pm_reset_assert(rst, PM_RESET_ACTION_RELEASE);
}

static int tx536_reset_request(struct reset_ctl *rst)
{
	struct tx536_reset_priv *priv = dev_get_priv(rst->dev);

	debug("%s(rst=%p) (id=%lu) (nr_reset=%d)\n", __func__,
		rst, rst->id, priv->nr_reset);

	if (rst->id >= priv->nr_reset)
		return -EINVAL;

	return 0;
}

static int tx536_reset_free(struct reset_ctl *rst)
{
	struct tx536_reset_priv *priv = dev_get_priv(rst->dev);

	debug("%s(rst=%p) (id=%lu) (nr_reset=%d)\n", __func__,
		rst, rst->id, priv->nr_reset);
	return 0;
}

static bool probed;
static int tx536_reset_probe(struct udevice *dev)
{
	struct tx536_reset_priv *priv = dev_get_priv(dev);
	fdt_addr_t addr;

	debug("---%s enter---\n", __func__);

	if (probed)
		return -ENOTSUPP;

	addr = dev_read_addr_index(dev, 0);
	if (addr == FDT_ADDR_T_NONE) {
		printf("%s get addr0 failed", __func__);
		return -EINVAL;
	}
	priv->top_rgu_base = (void *)addr;

	addr = dev_read_addr_index(dev, 1);
	if (addr == FDT_ADDR_T_NONE) {
		printf("get addr1 failed");
		return -EINVAL;
	}
	priv->mcu_rgu_base = (void *)addr;

	//printf("--top_rgu %p--\n", priv->top_rgu_base);
	//printf("--mcu_rgu %p--\n", priv->mcu_rgu_base);

	priv->nr_reset = TS_RST_MAX;
	probed = true;
	return 0;
}

const struct reset_ops tx536_reset_ops = {
	.request = tx536_reset_request,
	.rfree = tx536_reset_free,
	.rst_assert = tx536_reset_assert,
	.rst_deassert = tx536_reset_deassert,
};

static const struct udevice_id tx536_reset_ids[] = {
	{ .compatible = "ts,tx536-reset" },
	{ }
};

U_BOOT_DRIVER(ts_tx536_reset) = {
	.name		= "ts_tx536_reset",
	.id		= UCLASS_RESET,
	.of_match	= tx536_reset_ids,
	.ops		= &tx536_reset_ops,
	.probe		= tx536_reset_probe,
	.priv_auto_alloc_size	= sizeof(struct tx536_reset_priv),
};
