cmake_minimum_required(VERSION 2.8.5)

project(apps)

cmake_policy(SET CMP0054 NEW)

message(STATUS "ENABLE_MPP_TRACE:$ENV{ENABLE_MPP_TRACE}")

if($ENV{ENABLE_MPP_TRACE} EQUAL 1)
	add_definitions(-DENABLE_MPP_TRACE)
endif()

include (${CMAKE_CURRENT_SOURCE_DIR}/env.cmake)
include (${CMAKE_CURRENT_SOURCE_DIR}/common.cmake)

add_subdirectory (${APP_SRC_DIR}/build/venc              ${APP_SRC_DIR}/temp/venc)
add_subdirectory (${APP_SRC_DIR}/build/audio             ${APP_SRC_DIR}/temp/audio)
add_subdirectory (${APP_SRC_DIR}/build/trp/cve           ${APP_SRC_DIR}/temp/trp/cve)
add_subdirectory (${APP_SRC_DIR}/build/soft_vdec_lcd     ${APP_SRC_DIR}/temp/soft_vdec_lcd)
add_subdirectory (${APP_SRC_DIR}/build/tsalg_video        ${APP_SRC_DIR}/temp/tsalg_video)
add_subdirectory (${APP_SRC_DIR}/build/vdec        		${APP_SRC_DIR}/temp/vdec)
add_subdirectory (${APP_SRC_DIR}/build/tsalg_audio        ${APP_SRC_DIR}/temp/tsalg_audio)
add_subdirectory (${APP_SRC_DIR}/build/fastboot        	${APP_SRC_DIR}/temp/fastboot)
add_subdirectory (${APP_SRC_DIR}/build/drv/efuse             ${APP_SRC_DIR}/temp/drv/efuse)
add_subdirectory (${APP_SRC_DIR}/build/drv/lcd_spi           ${APP_SRC_DIR}/temp/drv/lcd_spi)
add_subdirectory (${APP_SRC_DIR}/build/region              ${APP_SRC_DIR}/temp/region)
add_subdirectory (${APP_SRC_DIR}/build/vo              ${APP_SRC_DIR}/temp/vo)
add_subdirectory (${APP_SRC_DIR}/build/vo_gui              ${APP_SRC_DIR}/temp/vo_gui)
add_subdirectory (${APP_SRC_DIR}/build/zoom         	${APP_SRC_DIR}/temp/zoom)
add_subdirectory (${APP_SRC_DIR}/build/drv/wdt              ${APP_SRC_DIR}/temp/drv/wdt)
add_subdirectory (${APP_SRC_DIR}/build/smart_encode        ${APP_SRC_DIR}/temp/smart_encode)
add_subdirectory (${APP_SRC_DIR}/build/vp_video_coder      ${APP_SRC_DIR}/temp/vp_video_coder)
add_subdirectory (${APP_SRC_DIR}/build/vp_voice     	   ${APP_SRC_DIR}/temp/vp_voice)
add_subdirectory (${APP_SRC_DIR}/build/vp_kws      		   ${APP_SRC_DIR}/temp/vp_kws)
add_subdirectory (${APP_SRC_DIR}/build/vp_algothrim        ${APP_SRC_DIR}/temp/vp_algothrim)
