# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_TS_SKE) += ts_ske.o
obj-$(CONFIG_TS_HASH) += ts_hash.o
obj-$(CONFIG_TS_PKE) += ts_pke/ts_eccp_curve.o ts_pke/ts_pke.o \
						ts_pke/ts_pke_prime.o ts_pke/ts_rsa.o \
						ts_pke/ts_sm2.o ts_pke/ts_trng.o \
						ts_pke/ts_utility.o